
// ─────────────────────────────────────────────────────────────────
// AUTO-GENERATED from Scout Supabase products — paste into
// medsync_newlocation_live.html replacing the DENOVO_SETS block
// ─────────────────────────────────────────────────────────────────

DENOVO_SETS.urgent_care = [
  // ── Medical Equipment (hardcoded — not in products table) ──
  {cat:'Medical Equipment',name:'Midmark Multiparameter Anesthesia Monitor',sku:'PM-9000',qty:2,section:'Surgery / Treatment'},
  {cat:'Medical Equipment',name:'Wildcat 750 Anesthesia Machine',sku:'Vetamac',qty:1,section:'Surgery'},
  {cat:'Medical Equipment',name:'IDEXX Catalyst One Chemistry Analyzer',sku:'IDEXX Catalyst One',qty:1,section:'Laboratory'},
  {cat:'Medical Equipment',name:'IDEXX ProCyte One Hematology Analyzer',sku:'IDEXX ProCyte One',qty:1,section:'Laboratory'},
  {cat:'Medical Equipment',name:'IDEXX SediVue Dx Urinalysis Analyzer',sku:'IDEXX SediVue Dx',qty:1,section:'Laboratory'},
  {cat:'Medical Equipment',name:'Covetrus ProMAX Infusion Pump',sku:'Covetrus ProMAX',qty:1,section:'Treatment / ICU'},
  {cat:'Medical Equipment',name:'VET-DOP 2 Doppler Blood Pressure',sku:'Vmed VET-DOP 2',qty:1,section:'Treatment'},
  {cat:'Medical Equipment',name:'TonoVet Plus Tonometer',sku:'TonoVet Plus',qty:1,section:'Exam / Treatment'},
  {cat:'Medical Equipment',name:'T-Top 10 Veterinary Autoclave',sku:'Tuttnauer T-Top 10',qty:1,section:'Surgery Prep'},
  {cat:'Medical Equipment',name:'Masimo Rad-57 Pulse CO-Oximeter',sku:'Masimo Rad-57',qty:1,section:'Treatment / ICU'},
  {cat:'Medical Equipment',name:'MidMark Platform Scale',sku:'MidMark 07-893-6514',qty:2,section:'Exam Rooms'},
  {cat:'Medical Equipment',name:'AlphaTRAK 2 Glucometer',sku:'AlphaTRAK 2',qty:2,section:'Treatment / Lab'},
  // ── Medications & consumables from Scout catalog ──
  {cat:'Analgesia',name:'Buprenorphine 0.3mg/ml',sku:'12496-0757-05',qty:8,section:'Pharmacy'},
  {cat:'Analgesia',name:'Gabapentin 100mg caps',sku:'65162-0469-50',qty:77,section:'Pharmacy'},
  {cat:'Analgesia',name:'Hydromorphone 2mg/ml',sku:'00409-1205-01',qty:12,section:'Pharmacy'},
  {cat:'Analgesia',name:'Tramadol 50mg tabs',sku:'00527-1394-01',qty:1,section:'Pharmacy'},
  {cat:'Sedation / Anesthesia',name:'Antisedan: 10ml (5mg/ml)',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Sedation / Anesthesia',name:'Dexdomitor: 10ml (0.5mg/ml)',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Sedation / Anesthesia',name:'Soda Lime, Carbon Dioxide Absorbent Granules 3lb Bottle',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Sedation / Anesthesia',name:'SodaLime Bag: 3lbs, 1 Each',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Sedation / Anesthesia',name:'Cuffed PVC Endotracheal Tube: Sterile, Clear, 4mm x 210mm, 1 Each',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Sedation / Anesthesia',name:'Cuffed PVC Endotracheal Tube: Sterile, Clear, 4.5mm x 225mm, 1 Each',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Sedation / Anesthesia',name:'Cuffed PVC Endotracheal Tube: Sterile, Transparent, 5mm x 245mm, 1 Each',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Sedation / Anesthesia',name:'Cuffed PVC Endotracheal Tube: Sterile, Clear, 5.5mm x 280mm, 1 Each',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Sedation / Anesthesia',name:'Cuffed PVC Endotracheal Tube: Sterile, Clear, 6mm x 290mm, 1 Each',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Sedation / Anesthesia',name:'Murphy Eye Cuffed Endotube: Clear, 7mm, Each',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Sedation / Anesthesia',name:'Murphy Eye Cuffed Endotube: Clear, 7.5mm, Each',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Sedation / Anesthesia',name:'Murphy Eye Cuffed Endotube: Clear, 8mm, Each',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Sedation / Anesthesia',name:'Murphy Eye Cuffed Endotube: Clear, 8.5mm, Each',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Sedation / Anesthesia',name:'Murphy Eye Cuffed Endotube: Clear, 9mm, Each',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Sedation / Anesthesia',name:'Murphy Eye Cuffed Endotube: Clear, 9.5mm, Each',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Sedation / Anesthesia',name:'Murphy Eye Cuffed Endotube: Clear, 10mm, Each',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Sedation / Anesthesia',name:'Resuscitator Bag: 2 Liter',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Sedation / Anesthesia',name:'Small Resuscitator Bag: 1 Liter',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Sedation / Anesthesia',name:'Miller Laryngoscope Blade: #1, Each',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Sedation / Anesthesia',name:'Miller Laryngoscope Blade: #2, Straight Shaft, Curved Tip,130mm, Each',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Sedation / Anesthesia',name:'Laryngoscopes: Handle Standard, Size C, Each',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Acepromazine 10mg/ml',sku:'13985-0018-01',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Alfaxan Multidose: 20ml (10mg/ml)',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Animax Ointment (Nystatin, Neomycin Sulfate, Thiostrepton, Triamcinolone Acetonide Ointment): 15 Ml',sku:'',qty:4,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Apomorphine HCl in AQ vehicle Injection Solution: 3 mg/ml, 10 ml',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Atipamezole Injection: 10mL (5mg/mL)',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Autoclave Pouch: 5.25X10 Seal, 200 Pvl, 200 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Baxter Sodium Chloride 0.9% Injection Bag: 50ml, 96 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Bio Glo Fluorescein Strips: 1mg, 300 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Biopsy Jar: 120ml (With 60ml Formalin), Each',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Blood Pressure Monitor Cuff: White Vinyl, Size 1',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Blood Pressure Monitor Cuff: White Vinyl, Size 2',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Blood Pressure Monitor Cuff: White Vinyl, Size 4',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Blue-Top Tube: 2.7 mL, Sodium Citrate',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Bullseye Pill Gun: Each',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Butorphanol Tartrate Injection 10mg/ml C4',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Capstar Tablets Blue: 11.4mg (Dogs 2-25lbs), 6 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Carprofen 50mg tabs',sku:'00010-3026-01',qty:46,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Carprofen Caplets: 25mg, 180 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Carprofen Caplets: 75mg, 180 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Carprofen Caplets: 100mg, 180 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Catalyst ALT: 12 Count',sku:'',qty:12,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Catalyst Chem 10 Clip: 12 Count',sku:'',qty:7,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Catalyst Chem 17 Clip: 12 Count',sku:'',qty:20,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Catalyst Pancreatic Lipase Test: 12 Count',sku:'',qty:9,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Catalyst Sample Cups: 450 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Catalyst Pipette Tips: 500 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Cautery, Disposable, High-Temperature, Fine-Tip, 2200 Degrees Fahrenheit 10 Count Pack',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Cefpoderm® (cefpodoxime proxetil tablets): 200 mg, 100 Count',sku:'',qty:13,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Cephalexin Capsules: 250Mg, 500 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Cephalexin Capsules: 500Mg, 500 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Cerenia Injectable Solution: 20ml',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Cerenia Tablets: 16mg,  10 x 4 Tablets',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Cerenia Tablets: 24mg, 10 x 4 Tablets',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Cerenia Tablets: 60mg, 10 x 4 Tablets',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Claro Otic Solution: 1 ml, 1 x 10 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Clavamox Drops: 15ml',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Clindamycin Hcl Capsules: 75Mg, 100 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Clindamycin Hcl Capsules: 150Mg, 100 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Constulose (Lactulose Solution, USP): 10 g/15 mL, Unflavored 946 mL Bottle',sku:'',qty:44,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Convenia Injectable: 10ml',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Convenia Sterile Water: 10mL in 23mL Vial',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Dexamethasone SP Injection: 1ml (4mg/ml), 25 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Dexmedetomidine 0.5mg/ml',sku:'13985-0028-01',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Dextrose 50% Injection Bottle: 500ml, 1 Each',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Diphenhydramine Injection: 10ml (50mg/ml)',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Diphenhydramine Capsules: 25mg, 100 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Disposable Otoscopic Cones: 4mm (Small), 50 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'DOUXO S3 PYO Wipes: 30 Count',sku:'',qty:3,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Doxycycline (as Hyclate) Oral Oil Suspension: 100 mg/ml, 100 ml',sku:'',qty:34,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Doxycycline Hyclate Capsules: 100Mg, 500 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Drontal Plus for Large Dogs (45+ lbs): 136mg, 30 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Drontal Plus for Medium Sized Dogs (26-60 lbs): 68mg, 50 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Drontal Plus for Puppies and Small Dogs (2-25 lbs): 22.7mg, 50 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Drontal Tablets Feline: 50 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Dual Indicator Self Sealing Sterilization Pouch: 3.5" x 9", 200 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Dual Indicator Self-Seal Sterilization Pouch: 7.5" x 13", 200 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Endosorb Anti-Diarrheal Tablets: 500 Count',sku:'',qty:125,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Endosorb Suspension: 1 Gallon',sku:'',qty:26,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Epinephrine Injection: 50Ml (1Mg/Ml)',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Erythromycin 0.5% Ophthalmic Ointment: 3.5G',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Famotidine Injection: 20ml (10mg/ml)',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Famotidine Tablets: 10Mg, 30 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Famotidine Tablets: 20Mg, 100 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Fatal Plus Solution: 250Ml',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Feliway Classic Diffuser Starter Kit with 30-Day Refill: 1 Kit',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Flumazenil Injection: 5mL (0.1mg/mL)',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Foley Catheter: 8fr x 24", 3ml Balloon Suture Wing',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Foley Silicone Catheter: 6fr x 24", 1.5ml Balloon Suture Wing',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Furosemide 1% Oral Syrup: 60ml (10mg/ml)',sku:'',qty:4,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Furosemide 5% Injection: 100ml (50mg/ml)',sku:'',qty:4,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Furosemide Tablets: 12.5mg, 500 Count',sku:'',qty:4,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Furosemide Tablets: 20Mg, 100 Count',sku:'',qty:4,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Gabapentin Capsules: 100Mg, 500 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Gabapentin Oral Oil Suspension: 100 mg/ml, 480 ml, Chicken',sku:'',qty:229,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Gabapentin Quad tab: 100 mg/tab, 100 Tablet, Chicken',sku:'',qty:16,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Gluture Topical Tissue Adhesive with 10 Applicators: 1.5mL',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Gold-Top, SST w/Gel: 4mL, 50 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Hydrogen Peroxide 3%: 1 Gallon, 1 Each',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Hydromorphone Injectable: 20ml (2mg/ml)',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Hypertonic Saline 7.2% Solution: 1000ml',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'ICU Sodium Chloride 0.9% Injection Bag: 250ml, 24 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'IDEXX UA Strips: 100 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Insulin Syringe with Needle: 0.3ml, U-100, 29g x 1/2", (10pks) 100 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Isopropyl Alcohol 70%: 1 Gallon, 4 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'IV Catheters - Angiocath 14gx3.25" FEP Teflon',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'IV Stand Deluxe: 54"-84"H, 4-Hooks, Each',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Jackson Pratt Silicone Drain with Trocar: 4.5mm, Each',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Jorgensen Surgical Masks, With Earloops: 50 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'K2-EDTA Lavender Vacuum Blood Collection Tube: 2ml, 100 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Ketamine HCl 10mg/ml',sku:'61703-0322-63',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Kimwipes: 4.5" x 8.5", 280 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Lactated Ringers Injection Bag: 1 Liter, 12 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Latex Free Face Mask: Level 1 Fluid, Ear Loops, Blue, 50 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Lavender-Top Tube, EDTA, 2mL',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Leash: Flat Blue 54", 12 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Levetiracetam Solution: 473ml (100mg/ml)',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Levetiracetam Tablets: 250mg, 120 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Lidocaine 2% Oral Topical Solution: 100Ml',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Lidocaine HCl Injection 2%: 100ml',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Luer Lock Syringe: 3cc, 100 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Mannitol 20% Injection: 100ml',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Maropitant Citrate 10mg/ml',sku:'61106-0001-01',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Maropitant Citrate Tablets for Dogs: 16 mg 4 Count',sku:'',qty:4,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Maropitant Citrate Tablets for Dogs: 24 mg, 4 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Maropitant Citrate Tablets: 60mg, 4 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Meloxicam 5mg/ml inj',sku:'13985-0516-01',qty:6,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Meloxicam Oral Suspension for Dogs: 10ml (1.5mg/ml)',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Methimazole Tablets: 5Mg, 100 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Methocarbamol Tablets: 500Mg, 100 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Metronidazole (as Benzoate) Oral Suspension: 100 mg/ml, 460 ml, Chicken Pot Pie',sku:'',qty:34,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Metronidazole (as Benzoate) Tiny Tabs: 50 mg/tab, 100 Tablet',sku:'',qty:13,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Metronidazole Tablets: 250Mg, 500 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Metronidazole Tablets: 500Mg, 500 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Microhematocrit Tube: 75mm, Sodium Heparinized, Red, 100 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Midazolam HCI Injection 5mg/mL, 10mL',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Mini Lavender-Top Tube (LTT) EDTA',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Mirataz® (Mirtazapine Transdermal Ointment): 5G, Each',sku:'',qty:3,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Mometamax Suspension: 15g, 12 Count',sku:'',qty:3,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Monoject Needle with Epoxy Insert: Rigid, 18g x 1", 100 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Monoject Needle with Plastic Hub: 22g x 3/4", Epoxy Insert, 100 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Monoject Needle with Plastic Hub: 25g x 5/8", Epoxy Insert, 100 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Monoject Oral Syringe: 3ml, clear, 100 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Monoject Syringe: 12ml, Luer Lock, 80 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Monoject Syringe: 20ml, Luer Lock, 50 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Monoject Syringe: 60ml, Catheter, 20 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Muzzle Nylon Canine: 25-40lbs, Royal Blue, 6"',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Nitrile Exam Gloves Powder Free: Large, 100 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Nitrile Exam Gloves Powder Free: Medium, 100 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Nitrile Exam Gloves: Powder Free, Small, 100 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Normosol R Injection: 1 Liter, 12 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Nutramax Proviable-Forte Digestive Health Supplement Kit for Cats and Small Dogs, Includes Multi-Strain Probiotics and Prebiotics, With 7 Strains of Beneficial Bacteria, 15 mL Paste and 15 Capsules',sku:'',qty:6,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Nutramax Proviable-Forte Digestive Health Supplement Kit for Medium and Large Dogs, Includes Multi-Strain Probiotics and Prebiotics, With 7 Strains of Beneficial Bacteria, 30 mL Paste and 15 Capsules',sku:'',qty:6,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Ofloxacin 0.3% Ophthalmic Solution: 5Ml',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Ondansetron 2mg/ml inj',sku:'63323-0185-01',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Ondansetron Tablets: 4Mg, 30 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Ondansetron Tablets: 8Mg, 30 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Onsior Tablets for Cats: 6 mg, 3 Doses x 10 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Optixcare Eye Lube Plus: 20g',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Otoscope Cones: Disposable, 4mm, 50 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Paper Cat Litter Tray: Disposable, 10.5 x 8.4 x 1 in , 500 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Pet Caddie Cardboard Pet Carrier: 12 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Pill Vial 1 Click 2 Way Cap: Green, 16 Dram, 150 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Posatex Otic Suspension: 15g, 12 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Prednisolone Acetate Ophthalmic Suspension: 1% , 5Ml',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Prednisone Tablets: 10Mg, 100 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Premium Feline Muzzle: Set of 3 (Small, Medium, Large)',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Proparacaine 0.5% Ophthalmic Solution: 15Ml',sku:'',qty:4,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Proviable Fiber Supplement Powder, 5-1 Fiber Blend with Prebiotics for Dogs and Cats',sku:'',qty:8,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'PureVent Pet Oxygen Mask: Large (Dogs over 25lbs)',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'PureVent Pet Oxygen Mask: Medium (Dogs up to 25lbs)',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'PureVent Pet Oxygen Mask: Small (For Cats, Kittens, & Puppies)',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Rescue Accelerated Hydrogen Peroxide Liquid Concentrate: 1 Gallon',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Rescue TB Wipes: 160 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'RX Destroyer All Purpose: Pro Series Bottle (~1,500 pills/bottle), 64oz',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Schirmer Tear Test Strip: 50 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'SediVue V70i Cartridges: 50 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Serum Separator Tube (SST) 4 mL GTT with Gel',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Sharps Container: Chimney Top Lid, 14 Quart',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Sharps Container: One Piece, 3.3 Quart',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Silver Sulfadiazine Cream 1% Tube: 50g',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Slippery Sam Tomcat Catheter: Closed End, 3.5fr x 5"',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Slippery Sam Tomcat Catheter: Closed End, 3.5fr x 6"',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Sodium Chloride 0.9% Irrigation: USP, Preservative-Free, 500ml, 18 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Sovereign Sterile Feeding Tube: 3.5fr x 16"',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Sovereign Sterile Feeding Tube: 5fr x 16"',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Sovereign Sterile Feeding Tube: 8fr x 22"',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Specialist Cast Padding: 3" x 4yd, 12 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Sterile Lubricating Jelly: 5g, 144 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Sterile Urine Container: 2 oz/60 mL',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Sterile Water Injection: 10ml, 25 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Stopcock 3-Way with Swivel Male Luer Lock: 50 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Sucralfate Tablets: 1G, 100 Count',sku:'',qty:4,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Surflo IV Catheter: 20ga x 1"',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Surflo IV Catheter: 20ga x 1.25"',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Surflo IV Catheter: 22ga x 1"',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Surflo IV Catheters: 18ga x 1.25"',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Surflo IV Catheters: 18ga x 2"',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Surgery Huck Towel: 17" x 33", 12 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Syringe (Soft Pack): Sterile, 5ml, Luer Lock, 100 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Syringe (Soft Pack): Sterile, 10ml, Luer Slip, 100 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Tobramycin Ophthalmic Solution: 5Ml (0.3%)',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Tomcat Catheter: Semi-Rigid, Closed End, with Adapter, 3.5fr x 5.5"',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Tongue Depressor: 6", 500 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Tonopen Tip Covers: Sterile, 150 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Toxiban Suspension: 240ml',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Trazodone Tablets: 100Mg, 100 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Triple Antibiotic Ointment: 1oz',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'TrizEDTA® Aqueous Flush: 4oz',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Trizultra+Keto® Flush 12Oz',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Vacutainer Safety-Lok Winged Blood Collection Set: Luer Adapter, 23g x 3/4", 12" Tubing, 50 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Viralys Powder: 100g',sku:'',qty:9,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Vitamin K Injection: 100ml (10mg/ml)',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Vitamin K1 Chewable Tablets: 50mg, 50 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Webcol Alcohol Prep Pads: Sterile, Medium, 200 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Wings Maxima Kennel Pads: High Absorbency, 23x36", 72 Count',sku:'',qty:1,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'ZYMOX  Otic with 1% Hydrocortisone: 1.25oz',sku:'',qty:1,section:'Pharmacy'},
  // ── Preventatives (UC only) ──
];

// ER: same types as UC, no preventatives, 2x medication quantities
const ER_EQUIPMENT_CATS = new Set(['Medical Equipment']);
DENOVO_SETS.er = [
  // ── Medical Equipment (same as UC + ICU additions) ──
  {cat:'Medical Equipment',name:'Midmark Multiparameter Anesthesia Monitor',sku:'PM-9000',qty:2,section:'Surgery / Treatment'},
  {cat:'Medical Equipment',name:'Wildcat 750 Anesthesia Machine',sku:'Vetamac',qty:1,section:'Surgery'},
  {cat:'Medical Equipment',name:'IDEXX Catalyst One Chemistry Analyzer',sku:'IDEXX Catalyst One',qty:1,section:'Laboratory'},
  {cat:'Medical Equipment',name:'IDEXX ProCyte One Hematology Analyzer',sku:'IDEXX ProCyte One',qty:1,section:'Laboratory'},
  {cat:'Medical Equipment',name:'IDEXX SediVue Dx Urinalysis Analyzer',sku:'IDEXX SediVue Dx',qty:1,section:'Laboratory'},
  {cat:'Medical Equipment',name:'Covetrus ProMAX Infusion Pump',sku:'Covetrus ProMAX',qty:1,section:'Treatment / ICU'},
  {cat:'Medical Equipment',name:'VET-DOP 2 Doppler Blood Pressure',sku:'Vmed VET-DOP 2',qty:1,section:'Treatment'},
  {cat:'Medical Equipment',name:'TonoVet Plus Tonometer',sku:'TonoVet Plus',qty:1,section:'Exam / Treatment'},
  {cat:'Medical Equipment',name:'T-Top 10 Veterinary Autoclave',sku:'Tuttnauer T-Top 10',qty:1,section:'Surgery Prep'},
  {cat:'Medical Equipment',name:'Masimo Rad-57 Pulse CO-Oximeter',sku:'Masimo Rad-57',qty:1,section:'Treatment / ICU'},
  {cat:'Medical Equipment',name:'MidMark Platform Scale',sku:'MidMark 07-893-6514',qty:2,section:'Exam Rooms'},
  {cat:'Medical Equipment',name:'AlphaTRAK 2 Glucometer',sku:'AlphaTRAK 2',qty:2,section:'Treatment / Lab'},
  {cat:'Medical Equipment',name:'Covetrus ProMAX Syringe Pump',sku:'Covetrus ProMAX Syringe',qty:2,section:'ICU'},
  {cat:'Medical Equipment',name:'EMMA Capnograph (EtCO2 Monitor)',sku:'Masimo EMMA',qty:2,section:'Surgery / ICU'},
  // ── Medications & consumables (2x UC quantities) ──
  {cat:'Analgesia',name:'Buprenorphine 0.3mg/ml',sku:'12496-0757-05',qty:16,section:'Pharmacy'},
  {cat:'Analgesia',name:'Gabapentin 100mg caps',sku:'65162-0469-50',qty:154,section:'Pharmacy'},
  {cat:'Analgesia',name:'Hydromorphone 2mg/ml',sku:'00409-1205-01',qty:24,section:'Pharmacy'},
  {cat:'Analgesia',name:'Tramadol 50mg tabs',sku:'00527-1394-01',qty:2,section:'Pharmacy'},
  {cat:'Sedation / Anesthesia',name:'Antisedan: 10ml (5mg/ml)',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Sedation / Anesthesia',name:'Dexdomitor: 10ml (0.5mg/ml)',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Sedation / Anesthesia',name:'Soda Lime, Carbon Dioxide Absorbent Granules 3lb Bottle',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Sedation / Anesthesia',name:'SodaLime Bag: 3lbs, 1 Each',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Sedation / Anesthesia',name:'Cuffed PVC Endotracheal Tube: Sterile, Clear, 4mm x 210mm, 1 Each',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Sedation / Anesthesia',name:'Cuffed PVC Endotracheal Tube: Sterile, Clear, 4.5mm x 225mm, 1 Each',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Sedation / Anesthesia',name:'Cuffed PVC Endotracheal Tube: Sterile, Transparent, 5mm x 245mm, 1 Each',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Sedation / Anesthesia',name:'Cuffed PVC Endotracheal Tube: Sterile, Clear, 5.5mm x 280mm, 1 Each',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Sedation / Anesthesia',name:'Cuffed PVC Endotracheal Tube: Sterile, Clear, 6mm x 290mm, 1 Each',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Sedation / Anesthesia',name:'Murphy Eye Cuffed Endotube: Clear, 7mm, Each',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Sedation / Anesthesia',name:'Murphy Eye Cuffed Endotube: Clear, 7.5mm, Each',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Sedation / Anesthesia',name:'Murphy Eye Cuffed Endotube: Clear, 8mm, Each',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Sedation / Anesthesia',name:'Murphy Eye Cuffed Endotube: Clear, 8.5mm, Each',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Sedation / Anesthesia',name:'Murphy Eye Cuffed Endotube: Clear, 9mm, Each',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Sedation / Anesthesia',name:'Murphy Eye Cuffed Endotube: Clear, 9.5mm, Each',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Sedation / Anesthesia',name:'Murphy Eye Cuffed Endotube: Clear, 10mm, Each',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Sedation / Anesthesia',name:'Resuscitator Bag: 2 Liter',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Sedation / Anesthesia',name:'Small Resuscitator Bag: 1 Liter',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Sedation / Anesthesia',name:'Miller Laryngoscope Blade: #1, Each',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Sedation / Anesthesia',name:'Miller Laryngoscope Blade: #2, Straight Shaft, Curved Tip,130mm, Each',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Sedation / Anesthesia',name:'Laryngoscopes: Handle Standard, Size C, Each',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Acepromazine 10mg/ml',sku:'13985-0018-01',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Alfaxan Multidose: 20ml (10mg/ml)',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Animax Ointment (Nystatin, Neomycin Sulfate, Thiostrepton, Triamcinolone Acetonide Ointment): 15 Ml',sku:'',qty:8,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Apomorphine HCl in AQ vehicle Injection Solution: 3 mg/ml, 10 ml',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Atipamezole Injection: 10mL (5mg/mL)',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Autoclave Pouch: 5.25X10 Seal, 200 Pvl, 200 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Baxter Sodium Chloride 0.9% Injection Bag: 50ml, 96 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Bio Glo Fluorescein Strips: 1mg, 300 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Biopsy Jar: 120ml (With 60ml Formalin), Each',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Blood Pressure Monitor Cuff: White Vinyl, Size 1',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Blood Pressure Monitor Cuff: White Vinyl, Size 2',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Blood Pressure Monitor Cuff: White Vinyl, Size 4',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Blue-Top Tube: 2.7 mL, Sodium Citrate',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Bullseye Pill Gun: Each',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Butorphanol Tartrate Injection 10mg/ml C4',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Capstar Tablets Blue: 11.4mg (Dogs 2-25lbs), 6 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Carprofen 50mg tabs',sku:'00010-3026-01',qty:92,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Carprofen Caplets: 25mg, 180 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Carprofen Caplets: 75mg, 180 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Carprofen Caplets: 100mg, 180 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Catalyst ALT: 12 Count',sku:'',qty:24,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Catalyst Chem 10 Clip: 12 Count',sku:'',qty:14,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Catalyst Chem 17 Clip: 12 Count',sku:'',qty:40,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Catalyst Pancreatic Lipase Test: 12 Count',sku:'',qty:18,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Catalyst Sample Cups: 450 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Catalyst Pipette Tips: 500 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Cautery, Disposable, High-Temperature, Fine-Tip, 2200 Degrees Fahrenheit 10 Count Pack',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Cefpoderm® (cefpodoxime proxetil tablets): 200 mg, 100 Count',sku:'',qty:26,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Cephalexin Capsules: 250Mg, 500 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Cephalexin Capsules: 500Mg, 500 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Cerenia Injectable Solution: 20ml',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Cerenia Tablets: 16mg,  10 x 4 Tablets',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Cerenia Tablets: 24mg, 10 x 4 Tablets',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Cerenia Tablets: 60mg, 10 x 4 Tablets',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Claro Otic Solution: 1 ml, 1 x 10 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Clavamox Drops: 15ml',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Clindamycin Hcl Capsules: 75Mg, 100 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Clindamycin Hcl Capsules: 150Mg, 100 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Constulose (Lactulose Solution, USP): 10 g/15 mL, Unflavored 946 mL Bottle',sku:'',qty:88,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Convenia Injectable: 10ml',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Convenia Sterile Water: 10mL in 23mL Vial',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Dexamethasone SP Injection: 1ml (4mg/ml), 25 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Dexmedetomidine 0.5mg/ml',sku:'13985-0028-01',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Dextrose 50% Injection Bottle: 500ml, 1 Each',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Diphenhydramine Injection: 10ml (50mg/ml)',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Diphenhydramine Capsules: 25mg, 100 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Disposable Otoscopic Cones: 4mm (Small), 50 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'DOUXO S3 PYO Wipes: 30 Count',sku:'',qty:6,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Doxycycline (as Hyclate) Oral Oil Suspension: 100 mg/ml, 100 ml',sku:'',qty:68,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Doxycycline Hyclate Capsules: 100Mg, 500 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Drontal Plus for Large Dogs (45+ lbs): 136mg, 30 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Drontal Plus for Medium Sized Dogs (26-60 lbs): 68mg, 50 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Drontal Plus for Puppies and Small Dogs (2-25 lbs): 22.7mg, 50 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Drontal Tablets Feline: 50 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Dual Indicator Self Sealing Sterilization Pouch: 3.5" x 9", 200 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Dual Indicator Self-Seal Sterilization Pouch: 7.5" x 13", 200 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Endosorb Anti-Diarrheal Tablets: 500 Count',sku:'',qty:250,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Endosorb Suspension: 1 Gallon',sku:'',qty:52,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Epinephrine Injection: 50Ml (1Mg/Ml)',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Erythromycin 0.5% Ophthalmic Ointment: 3.5G',sku:'',qty:4,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Famotidine Injection: 20ml (10mg/ml)',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Famotidine Tablets: 10Mg, 30 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Famotidine Tablets: 20Mg, 100 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Fatal Plus Solution: 250Ml',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Feliway Classic Diffuser Starter Kit with 30-Day Refill: 1 Kit',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Flumazenil Injection: 5mL (0.1mg/mL)',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Foley Catheter: 8fr x 24", 3ml Balloon Suture Wing',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Foley Silicone Catheter: 6fr x 24", 1.5ml Balloon Suture Wing',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Furosemide 1% Oral Syrup: 60ml (10mg/ml)',sku:'',qty:8,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Furosemide 5% Injection: 100ml (50mg/ml)',sku:'',qty:8,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Furosemide Tablets: 12.5mg, 500 Count',sku:'',qty:8,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Furosemide Tablets: 20Mg, 100 Count',sku:'',qty:8,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Gabapentin Capsules: 100Mg, 500 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Gabapentin Oral Oil Suspension: 100 mg/ml, 480 ml, Chicken',sku:'',qty:458,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Gabapentin Quad tab: 100 mg/tab, 100 Tablet, Chicken',sku:'',qty:32,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Gluture Topical Tissue Adhesive with 10 Applicators: 1.5mL',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Gold-Top, SST w/Gel: 4mL, 50 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Hydrogen Peroxide 3%: 1 Gallon, 1 Each',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Hydromorphone Injectable: 20ml (2mg/ml)',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Hypertonic Saline 7.2% Solution: 1000ml',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'ICU Sodium Chloride 0.9% Injection Bag: 250ml, 24 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'IDEXX UA Strips: 100 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Insulin Syringe with Needle: 0.3ml, U-100, 29g x 1/2", (10pks) 100 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Isopropyl Alcohol 70%: 1 Gallon, 4 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'IV Catheters - Angiocath 14gx3.25" FEP Teflon',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'IV Stand Deluxe: 54"-84"H, 4-Hooks, Each',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Jackson Pratt Silicone Drain with Trocar: 4.5mm, Each',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Jorgensen Surgical Masks, With Earloops: 50 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'K2-EDTA Lavender Vacuum Blood Collection Tube: 2ml, 100 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Ketamine HCl 10mg/ml',sku:'61703-0322-63',qty:4,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Kimwipes: 4.5" x 8.5", 280 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Lactated Ringers Injection Bag: 1 Liter, 12 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Latex Free Face Mask: Level 1 Fluid, Ear Loops, Blue, 50 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Lavender-Top Tube, EDTA, 2mL',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Leash: Flat Blue 54", 12 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Levetiracetam Solution: 473ml (100mg/ml)',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Levetiracetam Tablets: 250mg, 120 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Lidocaine 2% Oral Topical Solution: 100Ml',sku:'',qty:4,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Lidocaine HCl Injection 2%: 100ml',sku:'',qty:4,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Luer Lock Syringe: 3cc, 100 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Mannitol 20% Injection: 100ml',sku:'',qty:4,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Maropitant Citrate 10mg/ml',sku:'61106-0001-01',qty:4,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Maropitant Citrate Tablets for Dogs: 16 mg 4 Count',sku:'',qty:8,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Maropitant Citrate Tablets for Dogs: 24 mg, 4 Count',sku:'',qty:4,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Maropitant Citrate Tablets: 60mg, 4 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Meloxicam 5mg/ml inj',sku:'13985-0516-01',qty:12,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Meloxicam Oral Suspension for Dogs: 10ml (1.5mg/ml)',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Methimazole Tablets: 5Mg, 100 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Methocarbamol Tablets: 500Mg, 100 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Metronidazole (as Benzoate) Oral Suspension: 100 mg/ml, 460 ml, Chicken Pot Pie',sku:'',qty:68,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Metronidazole (as Benzoate) Tiny Tabs: 50 mg/tab, 100 Tablet',sku:'',qty:26,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Metronidazole Tablets: 250Mg, 500 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Metronidazole Tablets: 500Mg, 500 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Microhematocrit Tube: 75mm, Sodium Heparinized, Red, 100 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Midazolam HCI Injection 5mg/mL, 10mL',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Mini Lavender-Top Tube (LTT) EDTA',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Mirataz® (Mirtazapine Transdermal Ointment): 5G, Each',sku:'',qty:6,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Mometamax Suspension: 15g, 12 Count',sku:'',qty:6,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Monoject Needle with Epoxy Insert: Rigid, 18g x 1", 100 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Monoject Needle with Plastic Hub: 22g x 3/4", Epoxy Insert, 100 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Monoject Needle with Plastic Hub: 25g x 5/8", Epoxy Insert, 100 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Monoject Oral Syringe: 3ml, clear, 100 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Monoject Syringe: 12ml, Luer Lock, 80 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Monoject Syringe: 20ml, Luer Lock, 50 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Monoject Syringe: 60ml, Catheter, 20 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Muzzle Nylon Canine: 25-40lbs, Royal Blue, 6"',sku:'',qty:4,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Nitrile Exam Gloves Powder Free: Large, 100 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Nitrile Exam Gloves Powder Free: Medium, 100 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Nitrile Exam Gloves: Powder Free, Small, 100 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Normosol R Injection: 1 Liter, 12 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Nutramax Proviable-Forte Digestive Health Supplement Kit for Cats and Small Dogs, Includes Multi-Strain Probiotics and Prebiotics, With 7 Strains of Beneficial Bacteria, 15 mL Paste and 15 Capsules',sku:'',qty:12,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Nutramax Proviable-Forte Digestive Health Supplement Kit for Medium and Large Dogs, Includes Multi-Strain Probiotics and Prebiotics, With 7 Strains of Beneficial Bacteria, 30 mL Paste and 15 Capsules',sku:'',qty:12,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Ofloxacin 0.3% Ophthalmic Solution: 5Ml',sku:'',qty:4,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Ondansetron 2mg/ml inj',sku:'63323-0185-01',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Ondansetron Tablets: 4Mg, 30 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Ondansetron Tablets: 8Mg, 30 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Onsior Tablets for Cats: 6 mg, 3 Doses x 10 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Optixcare Eye Lube Plus: 20g',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Otoscope Cones: Disposable, 4mm, 50 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Paper Cat Litter Tray: Disposable, 10.5 x 8.4 x 1 in , 500 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Pet Caddie Cardboard Pet Carrier: 12 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Pill Vial 1 Click 2 Way Cap: Green, 16 Dram, 150 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Posatex Otic Suspension: 15g, 12 Count',sku:'',qty:4,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Prednisolone Acetate Ophthalmic Suspension: 1% , 5Ml',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Prednisone Tablets: 10Mg, 100 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Premium Feline Muzzle: Set of 3 (Small, Medium, Large)',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Proparacaine 0.5% Ophthalmic Solution: 15Ml',sku:'',qty:8,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Proviable Fiber Supplement Powder, 5-1 Fiber Blend with Prebiotics for Dogs and Cats',sku:'',qty:16,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'PureVent Pet Oxygen Mask: Large (Dogs over 25lbs)',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'PureVent Pet Oxygen Mask: Medium (Dogs up to 25lbs)',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'PureVent Pet Oxygen Mask: Small (For Cats, Kittens, & Puppies)',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Rescue Accelerated Hydrogen Peroxide Liquid Concentrate: 1 Gallon',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Rescue TB Wipes: 160 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'RX Destroyer All Purpose: Pro Series Bottle (~1,500 pills/bottle), 64oz',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Schirmer Tear Test Strip: 50 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'SediVue V70i Cartridges: 50 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Serum Separator Tube (SST) 4 mL GTT with Gel',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Sharps Container: Chimney Top Lid, 14 Quart',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Sharps Container: One Piece, 3.3 Quart',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Silver Sulfadiazine Cream 1% Tube: 50g',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Slippery Sam Tomcat Catheter: Closed End, 3.5fr x 5"',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Slippery Sam Tomcat Catheter: Closed End, 3.5fr x 6"',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Sodium Chloride 0.9% Irrigation: USP, Preservative-Free, 500ml, 18 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Sovereign Sterile Feeding Tube: 3.5fr x 16"',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Sovereign Sterile Feeding Tube: 5fr x 16"',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Sovereign Sterile Feeding Tube: 8fr x 22"',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Specialist Cast Padding: 3" x 4yd, 12 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Sterile Lubricating Jelly: 5g, 144 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Sterile Urine Container: 2 oz/60 mL',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Sterile Water Injection: 10ml, 25 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Stopcock 3-Way with Swivel Male Luer Lock: 50 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Sucralfate Tablets: 1G, 100 Count',sku:'',qty:8,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Surflo IV Catheter: 20ga x 1"',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Surflo IV Catheter: 20ga x 1.25"',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Surflo IV Catheter: 22ga x 1"',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Surflo IV Catheters: 18ga x 1.25"',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Surflo IV Catheters: 18ga x 2"',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Surgery Huck Towel: 17" x 33", 12 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Syringe (Soft Pack): Sterile, 5ml, Luer Lock, 100 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Syringe (Soft Pack): Sterile, 10ml, Luer Slip, 100 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Tobramycin Ophthalmic Solution: 5Ml (0.3%)',sku:'',qty:4,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Tomcat Catheter: Semi-Rigid, Closed End, with Adapter, 3.5fr x 5.5"',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Tongue Depressor: 6", 500 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Tonopen Tip Covers: Sterile, 150 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Toxiban Suspension: 240ml',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Trazodone Tablets: 100Mg, 100 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Triple Antibiotic Ointment: 1oz',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'TrizEDTA® Aqueous Flush: 4oz',sku:'',qty:4,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Trizultra+Keto® Flush 12Oz',sku:'',qty:4,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Vacutainer Safety-Lok Winged Blood Collection Set: Luer Adapter, 23g x 3/4", 12" Tubing, 50 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Viralys Powder: 100g',sku:'',qty:18,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Vitamin K Injection: 100ml (10mg/ml)',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Vitamin K1 Chewable Tablets: 50mg, 50 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Webcol Alcohol Prep Pads: Sterile, Medium, 200 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'Wings Maxima Kennel Pads: High Absorbency, 23x36", 72 Count',sku:'',qty:2,section:'Pharmacy'},
  {cat:'Miscellaneous',name:'ZYMOX  Otic with 1% Hydrocortisone: 1.25oz',sku:'',qty:2,section:'Pharmacy'},
  // ── Additional critical care medications ──
  {cat:'Injectables',name:'Epinephrine 1mg/mL',sku:'400002',qty:4,section:'Pharmacy'},
  {cat:'Injectables',name:'Atropine Injection',sku:'641602110',qty:4,section:'Pharmacy'},
  {cat:'Controlled Substances',name:'Propofol 10mg/mL',sku:'1117',qty:8,section:'Pharmacy'},
  {cat:'Controlled Substances',name:'Fentanyl 50mcg/mL',sku:'50383004316',qty:4,section:'Pharmacy'},
];
