-- VetSpire unit cost sync — Old Orchard (location 27390)
-- 197 products with non-zero prices
-- Run in: Supabase Dashboard → SQL Editor

BEGIN;

-- Step 1: Update by vetspire_product_id where already mapped
UPDATE public.products SET unit_price = 13.36, price_year = '2026' WHERE vetspire_product_id = '646466';
UPDATE public.products SET unit_price = 13.15, price_year = '2026' WHERE vetspire_product_id = '646467';
UPDATE public.products SET unit_price = 38.95, price_year = '2026' WHERE vetspire_product_id = '646620';
UPDATE public.products SET unit_price = 10.14, price_year = '2026' WHERE vetspire_product_id = '646468';
UPDATE public.products SET unit_price = 10.35, price_year = '2026' WHERE vetspire_product_id = '646470';
UPDATE public.products SET unit_price = 27.31, price_year = '2026' WHERE vetspire_product_id = '646622';
UPDATE public.products SET unit_price = 324.0, price_year = '2026' WHERE vetspire_product_id = '2596035';
UPDATE public.products SET unit_price = 84.95, price_year = '2026' WHERE vetspire_product_id = '646607';
UPDATE public.products SET unit_price = 49.35, price_year = '2026' WHERE vetspire_product_id = '838397';
UPDATE public.products SET unit_price = 15.4, price_year = '2026' WHERE vetspire_product_id = '646477';
UPDATE public.products SET unit_price = 15.4, price_year = '2026' WHERE vetspire_product_id = '646478';
UPDATE public.products SET unit_price = 15.4, price_year = '2026' WHERE vetspire_product_id = '646479';
UPDATE public.products SET unit_price = 63.8, price_year = '2026' WHERE vetspire_product_id = '646624';
UPDATE public.products SET unit_price = 16.1, price_year = '2026' WHERE vetspire_product_id = '646625';
UPDATE public.products SET unit_price = 83.75, price_year = '2026' WHERE vetspire_product_id = '646601';
UPDATE public.products SET unit_price = 56.2, price_year = '2026' WHERE vetspire_product_id = '646591';
UPDATE public.products SET unit_price = 78.83, price_year = '2026' WHERE vetspire_product_id = '646612';
UPDATE public.products SET unit_price = 42.5, price_year = '2026' WHERE vetspire_product_id = '646613';
UPDATE public.products SET unit_price = 22.5, price_year = '2026' WHERE vetspire_product_id = '646627';
UPDATE public.products SET unit_price = 40.55, price_year = '2026' WHERE vetspire_product_id = '646662';
UPDATE public.products SET unit_price = 12.56, price_year = '2026' WHERE vetspire_product_id = '646485';
UPDATE public.products SET unit_price = 11.6, price_year = '2026' WHERE vetspire_product_id = '646486';
UPDATE public.products SET unit_price = 12.02, price_year = '2026' WHERE vetspire_product_id = '646487';
UPDATE public.products SET unit_price = 36.6, price_year = '2026' WHERE vetspire_product_id = '628252';
UPDATE public.products SET unit_price = 36.6, price_year = '2026' WHERE vetspire_product_id = '628255';
UPDATE public.products SET unit_price = 152.0, price_year = '2026' WHERE vetspire_product_id = '628246';
UPDATE public.products SET unit_price = 223.0, price_year = '2026' WHERE vetspire_product_id = '628245';
UPDATE public.products SET unit_price = 108.0, price_year = '2026' WHERE vetspire_product_id = '1905936';
UPDATE public.products SET unit_price = 36.6, price_year = '2026' WHERE vetspire_product_id = '628259';
UPDATE public.products SET unit_price = 110.0, price_year = '2026' WHERE vetspire_product_id = '628260';
UPDATE public.products SET unit_price = 36.6, price_year = '2026' WHERE vetspire_product_id = '628267';
UPDATE public.products SET unit_price = 60.5, price_year = '2026' WHERE vetspire_product_id = '628247';
UPDATE public.products SET unit_price = 110.0, price_year = '2026' WHERE vetspire_product_id = '1626175';
UPDATE public.products SET unit_price = 36.6, price_year = '2026' WHERE vetspire_product_id = '970360';
UPDATE public.products SET unit_price = 110.0, price_year = '2026' WHERE vetspire_product_id = '628271';
UPDATE public.products SET unit_price = 15.25, price_year = '2026' WHERE vetspire_product_id = '646489';
UPDATE public.products SET unit_price = 11.4, price_year = '2026' WHERE vetspire_product_id = '646490';
UPDATE public.products SET unit_price = 10.77, price_year = '2026' WHERE vetspire_product_id = '646491';
UPDATE public.products SET unit_price = 107.55, price_year = '2026' WHERE vetspire_product_id = '646602';
UPDATE public.products SET unit_price = 12.98, price_year = '2026' WHERE vetspire_product_id = '646472';
UPDATE public.products SET unit_price = 14.91, price_year = '2026' WHERE vetspire_product_id = '646473';
UPDATE public.products SET unit_price = 17.01, price_year = '2026' WHERE vetspire_product_id = '646474';
UPDATE public.products SET unit_price = 11.6, price_year = '2026' WHERE vetspire_product_id = '646475';
UPDATE public.products SET unit_price = 60.86, price_year = '2026' WHERE vetspire_product_id = '646476';
UPDATE public.products SET unit_price = 11.61, price_year = '2026' WHERE vetspire_product_id = '646494';
UPDATE public.products SET unit_price = 34.36, price_year = '2026' WHERE vetspire_product_id = '646496';
UPDATE public.products SET unit_price = 87.0, price_year = '2026' WHERE vetspire_product_id = '628241';
UPDATE public.products SET unit_price = 87.0, price_year = '2026' WHERE vetspire_product_id = '628240';
UPDATE public.products SET unit_price = 335.5, price_year = '2026' WHERE vetspire_product_id = '1806627';
UPDATE public.products SET unit_price = 93.3, price_year = '2026' WHERE vetspire_product_id = '646655';
UPDATE public.products SET unit_price = 120.9, price_year = '2026' WHERE vetspire_product_id = '646656';
UPDATE public.products SET unit_price = 146.5, price_year = '2026' WHERE vetspire_product_id = '646657';
UPDATE public.products SET unit_price = 147.9, price_year = '2026' WHERE vetspire_product_id = '646658';
UPDATE public.products SET unit_price = 17.3, price_year = '2026' WHERE vetspire_product_id = '646629';
UPDATE public.products SET unit_price = 98.5, price_year = '2026' WHERE vetspire_product_id = '646631';
UPDATE public.products SET unit_price = 14.55, price_year = '2026' WHERE vetspire_product_id = '646632';
UPDATE public.products SET unit_price = 10.22, price_year = '2026' WHERE vetspire_product_id = '646505';
UPDATE public.products SET unit_price = 10.24, price_year = '2026' WHERE vetspire_product_id = '646506';
UPDATE public.products SET unit_price = 27.45, price_year = '2026' WHERE vetspire_product_id = '646633';
UPDATE public.products SET unit_price = 10.21, price_year = '2026' WHERE vetspire_product_id = '646504';
UPDATE public.products SET unit_price = 56.4, price_year = '2026' WHERE vetspire_product_id = '646598';
UPDATE public.products SET unit_price = 64.09, price_year = '2026' WHERE vetspire_product_id = '646684';
UPDATE public.products SET unit_price = 62.5, price_year = '2026' WHERE vetspire_product_id = '646683';
UPDATE public.products SET unit_price = 50.92, price_year = '2026' WHERE vetspire_product_id = '646685';
UPDATE public.products SET unit_price = 10.56, price_year = '2026' WHERE vetspire_product_id = '845001';
UPDATE public.products SET unit_price = 13.5, price_year = '2026' WHERE vetspire_product_id = '845776';
UPDATE public.products SET unit_price = 84.42, price_year = '2026' WHERE vetspire_product_id = '667665';
UPDATE public.products SET unit_price = 51.37, price_year = '2026' WHERE vetspire_product_id = '667664';
UPDATE public.products SET unit_price = 26.21, price_year = '2026' WHERE vetspire_product_id = '646510';
UPDATE public.products SET unit_price = 29.74, price_year = '2026' WHERE vetspire_product_id = '646509';
UPDATE public.products SET unit_price = 7.44, price_year = '2026' WHERE vetspire_product_id = '1162107';
UPDATE public.products SET unit_price = 11.4, price_year = '2026' WHERE vetspire_product_id = '646397';
UPDATE public.products SET unit_price = 13.0, price_year = '2026' WHERE vetspire_product_id = '646398';
UPDATE public.products SET unit_price = 14.72, price_year = '2026' WHERE vetspire_product_id = '646399';
UPDATE public.products SET unit_price = 18.52, price_year = '2026' WHERE vetspire_product_id = '646400';
UPDATE public.products SET unit_price = 22.48, price_year = '2026' WHERE vetspire_product_id = '646401';
UPDATE public.products SET unit_price = 9.52, price_year = '2026' WHERE vetspire_product_id = '646403';
UPDATE public.products SET unit_price = 110.29, price_year = '2026' WHERE vetspire_product_id = '670553';
UPDATE public.products SET unit_price = 10.21, price_year = '2026' WHERE vetspire_product_id = '1743751';
UPDATE public.products SET unit_price = 11.19, price_year = '2026' WHERE vetspire_product_id = '1067430';
UPDATE public.products SET unit_price = 19.66, price_year = '2026' WHERE vetspire_product_id = '923212';
UPDATE public.products SET unit_price = 123.64, price_year = '2026' WHERE vetspire_product_id = '670551';
UPDATE public.products SET unit_price = 19.4, price_year = '2026' WHERE vetspire_product_id = '646635';
UPDATE public.products SET unit_price = 69.89, price_year = '2026' WHERE vetspire_product_id = '646610';
UPDATE public.products SET unit_price = 67.95, price_year = '2026' WHERE vetspire_product_id = '1069602';
UPDATE public.products SET unit_price = 35.12, price_year = '2026' WHERE vetspire_product_id = '670007';
UPDATE public.products SET unit_price = 33.04, price_year = '2026' WHERE vetspire_product_id = '670006';
UPDATE public.products SET unit_price = 10.7, price_year = '2026' WHERE vetspire_product_id = '981759';
UPDATE public.products SET unit_price = 18.63, price_year = '2026' WHERE vetspire_product_id = '646636';
UPDATE public.products SET unit_price = 11.12, price_year = '2026' WHERE vetspire_product_id = '646519';
UPDATE public.products SET unit_price = 19.95, price_year = '2026' WHERE vetspire_product_id = '646637';
UPDATE public.products SET unit_price = 11.05, price_year = '2026' WHERE vetspire_product_id = '646520';
UPDATE public.products SET unit_price = 17.3, price_year = '2026' WHERE vetspire_product_id = '646638';
UPDATE public.products SET unit_price = 11.4, price_year = '2026' WHERE vetspire_product_id = '667659';
UPDATE public.products SET unit_price = 10.49, price_year = '2026' WHERE vetspire_product_id = '646523';
UPDATE public.products SET unit_price = 14.2, price_year = '2026' WHERE vetspire_product_id = '868294';
UPDATE public.products SET unit_price = 10.61, price_year = '2026' WHERE vetspire_product_id = '646524';
UPDATE public.products SET unit_price = 11.98, price_year = '2026' WHERE vetspire_product_id = '646525';
UPDATE public.products SET unit_price = 10.08, price_year = '2026' WHERE vetspire_product_id = '649056';
UPDATE public.products SET unit_price = 15.7, price_year = '2026' WHERE vetspire_product_id = '1933389';
UPDATE public.products SET unit_price = 13.32, price_year = '2026' WHERE vetspire_product_id = '667670';
UPDATE public.products SET unit_price = 12.69, price_year = '2026' WHERE vetspire_product_id = '1848212';
UPDATE public.products SET unit_price = 15.19, price_year = '2026' WHERE vetspire_product_id = '646677';
UPDATE public.products SET unit_price = 10.7, price_year = '2026' WHERE vetspire_product_id = '646458';
UPDATE public.products SET unit_price = 28.35, price_year = '2026' WHERE vetspire_product_id = '837592';
UPDATE public.products SET unit_price = 14.52, price_year = '2026' WHERE vetspire_product_id = '646412';
UPDATE public.products SET unit_price = 23.8, price_year = '2026' WHERE vetspire_product_id = '646616';
UPDATE public.products SET unit_price = 10.21, price_year = '2026' WHERE vetspire_product_id = '646532';
UPDATE public.products SET unit_price = 44.93, price_year = '2026' WHERE vetspire_product_id = '646592';
UPDATE public.products SET unit_price = 11.12, price_year = '2026' WHERE vetspire_product_id = '646530';
UPDATE public.products SET unit_price = 10.28, price_year = '2026' WHERE vetspire_product_id = '646529';
UPDATE public.products SET unit_price = 14.87, price_year = '2026' WHERE vetspire_product_id = '646644';
UPDATE public.products SET unit_price = 11.12, price_year = '2026' WHERE vetspire_product_id = '646531';
UPDATE public.products SET unit_price = 16.39, price_year = '2026' WHERE vetspire_product_id = '646413';
UPDATE public.products SET unit_price = 24.76, price_year = '2026' WHERE vetspire_product_id = '646538';
UPDATE public.products SET unit_price = 25.2, price_year = '2026' WHERE vetspire_product_id = '646539';
UPDATE public.products SET unit_price = 31.2, price_year = '2026' WHERE vetspire_product_id = '646540';
UPDATE public.products SET unit_price = 65.25, price_year = '2026' WHERE vetspire_product_id = '2333592';
UPDATE public.products SET unit_price = 80.17, price_year = '2026' WHERE vetspire_product_id = '646542';
UPDATE public.products SET unit_price = 1.75, price_year = '2026' WHERE vetspire_product_id = '1743626';
UPDATE public.products SET unit_price = 161.29, price_year = '2026' WHERE vetspire_product_id = '646617';
UPDATE public.products SET unit_price = 11.26, price_year = '2026' WHERE vetspire_product_id = '646543';
UPDATE public.products SET unit_price = 10.84, price_year = '2026' WHERE vetspire_product_id = '646544';
UPDATE public.products SET unit_price = 10.35, price_year = '2026' WHERE vetspire_product_id = '646545';
UPDATE public.products SET unit_price = 10.91, price_year = '2026' WHERE vetspire_product_id = '646546';
UPDATE public.products SET unit_price = 11.96, price_year = '2026' WHERE vetspire_product_id = '646548';
UPDATE public.products SET unit_price = 13.64, price_year = '2026' WHERE vetspire_product_id = '646547';
UPDATE public.products SET unit_price = 55.0, price_year = '2026' WHERE vetspire_product_id = '523819';
UPDATE public.products SET unit_price = 18.3, price_year = '2026' WHERE vetspire_product_id = '646618';
UPDATE public.products SET unit_price = 16.5, price_year = '2026' WHERE vetspire_product_id = '1140862';
UPDATE public.products SET unit_price = 93.61, price_year = '2026' WHERE vetspire_product_id = '646550';
UPDATE public.products SET unit_price = 89.5, price_year = '2026' WHERE vetspire_product_id = '646604';
UPDATE public.products SET unit_price = 52.72, price_year = '2026' WHERE vetspire_product_id = '646647';
UPDATE public.products SET unit_price = 72.98, price_year = '2026' WHERE vetspire_product_id = '1069601';
UPDATE public.products SET unit_price = 72.98, price_year = '2026' WHERE vetspire_product_id = '1069600';
UPDATE public.products SET unit_price = 72.98, price_year = '2026' WHERE vetspire_product_id = '1069598';
UPDATE public.products SET unit_price = 52.98, price_year = '2026' WHERE vetspire_product_id = '1333328';
UPDATE public.products SET unit_price = 62.01, price_year = '2026' WHERE vetspire_product_id = '646599';
UPDATE public.products SET unit_price = 69.2, price_year = '2026' WHERE vetspire_product_id = '646593';
UPDATE public.products SET unit_price = 182.5, price_year = '2026' WHERE vetspire_product_id = '646648';
UPDATE public.products SET unit_price = 10.98, price_year = '2026' WHERE vetspire_product_id = '646554';
UPDATE public.products SET unit_price = 11.4, price_year = '2026' WHERE vetspire_product_id = '771653';
UPDATE public.products SET unit_price = 16.81, price_year = '2026' WHERE vetspire_product_id = '646649';
UPDATE public.products SET unit_price = 62.8, price_year = '2026' WHERE vetspire_product_id = '646594';
UPDATE public.products SET unit_price = 32.43, price_year = '2026' WHERE vetspire_product_id = '646556';
UPDATE public.products SET unit_price = 44.02, price_year = '2026' WHERE vetspire_product_id = '646557';
UPDATE public.products SET unit_price = 55.05, price_year = '2026' WHERE vetspire_product_id = '646558';
UPDATE public.products SET unit_price = 17.1, price_year = '2026' WHERE vetspire_product_id = '646559';
UPDATE public.products SET unit_price = 106.57, price_year = '2026' WHERE vetspire_product_id = '646605';
UPDATE public.products SET unit_price = 10.4, price_year = '2026' WHERE vetspire_product_id = '646566';
UPDATE public.products SET unit_price = 103.0, price_year = '2026' WHERE vetspire_product_id = '646596';
UPDATE public.products SET unit_price = 11.19, price_year = '2026' WHERE vetspire_product_id = '646564';
UPDATE public.products SET unit_price = 10.56, price_year = '2026' WHERE vetspire_product_id = '646568';
UPDATE public.products SET unit_price = 10.56, price_year = '2026' WHERE vetspire_product_id = '646590';
UPDATE public.products SET unit_price = 60.7, price_year = '2026' WHERE vetspire_product_id = '646573';
UPDATE public.products SET unit_price = 66.7, price_year = '2026' WHERE vetspire_product_id = '646574';
UPDATE public.products SET unit_price = 53.0, price_year = '2026' WHERE vetspire_product_id = '871643';
UPDATE public.products SET unit_price = 79.0, price_year = '2026' WHERE vetspire_product_id = '646383';
UPDATE public.products SET unit_price = 157.0, price_year = '2026' WHERE vetspire_product_id = '646384';
UPDATE public.products SET unit_price = 53.0, price_year = '2026' WHERE vetspire_product_id = '646385';
UPDATE public.products SET unit_price = 10.28, price_year = '2026' WHERE vetspire_product_id = '886431';
UPDATE public.products SET unit_price = 6.0, price_year = '2026' WHERE vetspire_product_id = '680801';
UPDATE public.products SET unit_price = 18.0, price_year = '2026' WHERE vetspire_product_id = '680803';
UPDATE public.products SET unit_price = 61.0, price_year = '2026' WHERE vetspire_product_id = '646676';
UPDATE public.products SET unit_price = 53.59, price_year = '2026' WHERE vetspire_product_id = '646674';
UPDATE public.products SET unit_price = 59.74, price_year = '2026' WHERE vetspire_product_id = '646675';
UPDATE public.products SET unit_price = 59.35, price_year = '2026' WHERE vetspire_product_id = '886430';
UPDATE public.products SET unit_price = 56.95, price_year = '2026' WHERE vetspire_product_id = '646576';
UPDATE public.products SET unit_price = 12.85, price_year = '2026' WHERE vetspire_product_id = '646680';
UPDATE public.products SET unit_price = 103.0, price_year = '2026' WHERE vetspire_product_id = '628229';
UPDATE public.products SET unit_price = 99.5, price_year = '2026' WHERE vetspire_product_id = '628237';
UPDATE public.products SET unit_price = 112.0, price_year = '2026' WHERE vetspire_product_id = '628234';
UPDATE public.products SET unit_price = 106.5, price_year = '2026' WHERE vetspire_product_id = '628233';
UPDATE public.products SET unit_price = 152.74, price_year = '2026' WHERE vetspire_product_id = '873304';
UPDATE public.products SET unit_price = 177.8, price_year = '2026' WHERE vetspire_product_id = '2148179';
UPDATE public.products SET unit_price = 11.61, price_year = '2026' WHERE vetspire_product_id = '1743750';
UPDATE public.products SET unit_price = 86.62, price_year = '2026' WHERE vetspire_product_id = '646595';
UPDATE public.products SET unit_price = 59.7, price_year = '2026' WHERE vetspire_product_id = '646597';
UPDATE public.products SET unit_price = 10.5, price_year = '2026' WHERE vetspire_product_id = '646579';
UPDATE public.products SET unit_price = 10.56, price_year = '2026' WHERE vetspire_product_id = '646580';
UPDATE public.products SET unit_price = 10.49, price_year = '2026' WHERE vetspire_product_id = '646581';
UPDATE public.products SET unit_price = 48.67, price_year = '2026' WHERE vetspire_product_id = '1069603';
UPDATE public.products SET unit_price = 75.7, price_year = '2026' WHERE vetspire_product_id = '646608';
UPDATE public.products SET unit_price = 15.5, price_year = '2026' WHERE vetspire_product_id = '628242';
UPDATE public.products SET unit_price = 41.5, price_year = '2026' WHERE vetspire_product_id = '628426';
UPDATE public.products SET unit_price = 53.0, price_year = '2026' WHERE vetspire_product_id = '646376';
UPDATE public.products SET unit_price = 69.0, price_year = '2026' WHERE vetspire_product_id = '646377';
UPDATE public.products SET unit_price = 69.0, price_year = '2026' WHERE vetspire_product_id = '646378';
UPDATE public.products SET unit_price = 62.0, price_year = '2026' WHERE vetspire_product_id = '646379';
UPDATE public.products SET unit_price = 50.0, price_year = '2026' WHERE vetspire_product_id = '646380';
UPDATE public.products SET unit_price = 53.0, price_year = '2026' WHERE vetspire_product_id = '646381';
UPDATE public.products SET unit_price = 59.0, price_year = '2026' WHERE vetspire_product_id = '646374';
UPDATE public.products SET unit_price = 95.0, price_year = '2026' WHERE vetspire_product_id = '646373';
UPDATE public.products SET unit_price = 96.85, price_year = '2026' WHERE vetspire_product_id = '646584';
UPDATE public.products SET unit_price = 11.19, price_year = '2026' WHERE vetspire_product_id = '837585';
UPDATE public.products SET unit_price = 12.94, price_year = '2026' WHERE vetspire_product_id = '646585';
UPDATE public.products SET unit_price = 61.21, price_year = '2026' WHERE vetspire_product_id = '646587';

-- Step 2: Map + update by name where vetspire_product_id not yet set
UPDATE public.products SET unit_price = 13.36, vetspire_product_id = '646466', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Albon (Sulfadimethoxine) 250 mg tablets');
UPDATE public.products SET unit_price = 13.15, vetspire_product_id = '646467', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Albuterol HFA 90 mcg');
UPDATE public.products SET unit_price = 38.95, vetspire_product_id = '646620', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Alfaxalone Inj 10 mg/ml');
UPDATE public.products SET unit_price = 10.14, vetspire_product_id = '646468', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Aluminum Hydroxide 64 mg/ml solution');
UPDATE public.products SET unit_price = 10.35, vetspire_product_id = '646470', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Amlodipine 2.5 mg tablets');
UPDATE public.products SET unit_price = 27.31, vetspire_product_id = '646622', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Amp+Sulbactam Inj 30 mg/ml (1.5 g vial)');
UPDATE public.products SET unit_price = 324.0, vetspire_product_id = '2596035', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Anemia RealPCR™ Panel—Canine (2938)');
UPDATE public.products SET unit_price = 84.95, vetspire_product_id = '646607', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Animax Ointment (15 ml)');
UPDATE public.products SET unit_price = 49.35, vetspire_product_id = '838397', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Apomorphine HCl 3 mg/ml');
UPDATE public.products SET unit_price = 15.4, vetspire_product_id = '646477', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Apoquel 16 mg tablets');
UPDATE public.products SET unit_price = 15.4, vetspire_product_id = '646478', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Apoquel 3.6 mg tablets');
UPDATE public.products SET unit_price = 15.4, vetspire_product_id = '646479', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Apoquel 5.4 mg tablets');
UPDATE public.products SET unit_price = 63.8, vetspire_product_id = '646624', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Atipamezole HCl  Inj 5 mg/ml');
UPDATE public.products SET unit_price = 16.1, vetspire_product_id = '646625', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Atropine Inj 0.54 mg/ml');
UPDATE public.products SET unit_price = 83.75, vetspire_product_id = '646601', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Baytril Otic (15 ml)');
UPDATE public.products SET unit_price = 56.2, vetspire_product_id = '646591', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('BNP Opthalmic Ointment (3.5 gm)');
UPDATE public.products SET unit_price = 78.83, vetspire_product_id = '646612', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Buprenorphine  Inj 0.3 mg/ml');
UPDATE public.products SET unit_price = 42.5, vetspire_product_id = '646613', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Butorphanol Inj 10 mg/ml');
UPDATE public.products SET unit_price = 22.5, vetspire_product_id = '646627', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Calcium Gluconate 10% Inj (100 mg/ml)');
UPDATE public.products SET unit_price = 40.55, vetspire_product_id = '646662', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Capstar Tablet 11.4 mg (Cats  and Small  Dogs 2 to 25 lbs)');
UPDATE public.products SET unit_price = 12.56, vetspire_product_id = '646485', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Carprofen 100 mg tablets');
UPDATE public.products SET unit_price = 11.6, vetspire_product_id = '646486', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Carprofen 25 mg tablets');
UPDATE public.products SET unit_price = 12.02, vetspire_product_id = '646487', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Carprofen 75 mg tablets');
UPDATE public.products SET unit_price = 36.6, vetspire_product_id = '628252', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Catalyst Alkaline Aminotransferase (ALT)');
UPDATE public.products SET unit_price = 36.6, vetspire_product_id = '628255', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Catalyst Blood Urea Nitrogen (BUN)');
UPDATE public.products SET unit_price = 152.0, vetspire_product_id = '628246', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Catalyst Chem 10');
UPDATE public.products SET unit_price = 223.0, vetspire_product_id = '628245', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Catalyst Chem 17');
UPDATE public.products SET unit_price = 108.0, vetspire_product_id = '1905936', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Catalyst Cortisol (CORT)');
UPDATE public.products SET unit_price = 36.6, vetspire_product_id = '628259', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Catalyst Creatinine (CREA)');
UPDATE public.products SET unit_price = 110.0, vetspire_product_id = '628260', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Catalyst Fructosamine (FRU)');
UPDATE public.products SET unit_price = 36.6, vetspire_product_id = '628267', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Catalyst Inorganic Phosphate (PHOS)');
UPDATE public.products SET unit_price = 60.5, vetspire_product_id = '628247', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Catalyst Lytes 4');
UPDATE public.products SET unit_price = 110.0, vetspire_product_id = '1626175', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Catalyst Pancreatic Lipase  (PL)');
UPDATE public.products SET unit_price = 36.6, vetspire_product_id = '970360', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Catalyst Total Bilirubin (TBILI)');
UPDATE public.products SET unit_price = 110.0, vetspire_product_id = '628271', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Catalyst Total T4 (TT4)');
UPDATE public.products SET unit_price = 15.25, vetspire_product_id = '646489', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Cefpodoxime 200 mg tablets');
UPDATE public.products SET unit_price = 11.4, vetspire_product_id = '646490', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Cephalexin 250 mg capsules');
UPDATE public.products SET unit_price = 10.77, vetspire_product_id = '646491', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Cephalexin 500 mg capsules');
UPDATE public.products SET unit_price = 107.55, vetspire_product_id = '646602', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Claro Otic (1 ml)');
UPDATE public.products SET unit_price = 12.98, vetspire_product_id = '646472', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Clavacillin 125 mg tablets');
UPDATE public.products SET unit_price = 14.91, vetspire_product_id = '646473', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Clavacillin 250 mg tablets');
UPDATE public.products SET unit_price = 17.01, vetspire_product_id = '646474', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Clavacillin 375 mg tablets');
UPDATE public.products SET unit_price = 11.6, vetspire_product_id = '646475', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Clavacillin 62.5 mg tablets');
UPDATE public.products SET unit_price = 60.86, vetspire_product_id = '646476', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Clavacillin  Susp 62.5 mg/ml (15 ml bottle)');
UPDATE public.products SET unit_price = 11.61, vetspire_product_id = '646494', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Clindamycin 150 mg capsules');
UPDATE public.products SET unit_price = 34.36, vetspire_product_id = '646496', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Clindamycin Susp 25 mg/ml (20 ml bottle)');
UPDATE public.products SET unit_price = 87.0, vetspire_product_id = '628241', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Coag Dx Citrate Activated Partial Thromboplastin Time (aPTT)');
UPDATE public.products SET unit_price = 87.0, vetspire_product_id = '628240', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Coag Dx Citrate Prothrombin Time (PT)');
UPDATE public.products SET unit_price = 335.5, vetspire_product_id = '1806627', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Cryptococcus Antigen by Latex Agglutination (718)');
UPDATE public.products SET unit_price = 93.3, vetspire_product_id = '646655', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Cytopoint 10 mg (1 ml vial)');
UPDATE public.products SET unit_price = 120.9, vetspire_product_id = '646656', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Cytopoint 20 mg (1 ml vial)');
UPDATE public.products SET unit_price = 146.5, vetspire_product_id = '646657', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Cytopoint 30 mg (1 ml vial)');
UPDATE public.products SET unit_price = 147.9, vetspire_product_id = '646658', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Cytopoint 40 mg (1 ml vial)');
UPDATE public.products SET unit_price = 17.3, vetspire_product_id = '646629', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Dexamethasone-SP Inj 4 mg/ml');
UPDATE public.products SET unit_price = 98.5, vetspire_product_id = '646631', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Dexmedetomidine Inj 0.5 mg/ml');
UPDATE public.products SET unit_price = 14.55, vetspire_product_id = '646632', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Dextrose Solu Inj 50%');
UPDATE public.products SET unit_price = 10.22, vetspire_product_id = '646505', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Diphenhydramine 25 mg capsules');
UPDATE public.products SET unit_price = 10.24, vetspire_product_id = '646506', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Diphenhydramine 50 mg capsules');
UPDATE public.products SET unit_price = 27.45, vetspire_product_id = '646633', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Diphenhydramine Inj 50 mg/ml');
UPDATE public.products SET unit_price = 10.21, vetspire_product_id = '646504', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Diphenhydramine Syrup 12.5 mg/5 ml');
UPDATE public.products SET unit_price = 56.4, vetspire_product_id = '646598', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Dorzolamide Timolol 2-0.5% Solu (10 ml)');
UPDATE public.products SET unit_price = 64.09, vetspire_product_id = '646684', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Douxo S3 PYO Mousse (5.1 oz)');
UPDATE public.products SET unit_price = 62.5, vetspire_product_id = '646683', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Douxo S3 PYO Shampoo (6.7 oz)');
UPDATE public.products SET unit_price = 50.92, vetspire_product_id = '646685', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Douxo S3 PYO Wipes (30 ct)');
UPDATE public.products SET unit_price = 10.56, vetspire_product_id = '845001', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Doxycycline 100 mg tablets');
UPDATE public.products SET unit_price = 13.5, vetspire_product_id = '845776', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Doxycycline Solu 100 mg/ml');
UPDATE public.products SET unit_price = 84.42, vetspire_product_id = '667665', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Drontal (Praziquantel/Pyrantel Pamoate/Febantel) PLUS for Large Dogs');
UPDATE public.products SET unit_price = 51.37, vetspire_product_id = '667664', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Drontal (Praziquantel/Pyrantel Pamoate/Febantel) PLUS for Medium Dogs');
UPDATE public.products SET unit_price = 26.21, vetspire_product_id = '646510', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Drontal (Praziquantel/Pyrantel Pamoate/Febantel) PLUS for Puppies & Small Dogs');
UPDATE public.products SET unit_price = 29.74, vetspire_product_id = '646509', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Drontal (Praziquantel/Pyrantel Pamoate) for Cats and Kittens');
UPDATE public.products SET unit_price = 7.44, vetspire_product_id = '1162107', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('E-Collar - 10 cm');
UPDATE public.products SET unit_price = 11.4, vetspire_product_id = '646397', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('E-Collar - 12 cm');
UPDATE public.products SET unit_price = 13.0, vetspire_product_id = '646398', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('E-Collar - 15 cm');
UPDATE public.products SET unit_price = 14.72, vetspire_product_id = '646399', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('E-Collar - 20 cm');
UPDATE public.products SET unit_price = 18.52, vetspire_product_id = '646400', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('E-Collar - 25 cm');
UPDATE public.products SET unit_price = 22.48, vetspire_product_id = '646401', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('E-Collar - 30 cm');
UPDATE public.products SET unit_price = 9.52, vetspire_product_id = '646403', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('E-Collar - 7.5 cm');
UPDATE public.products SET unit_price = 110.29, vetspire_product_id = '670553', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Elura 20 mg/ml (15 ml)');
UPDATE public.products SET unit_price = 10.21, vetspire_product_id = '1743751', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Endosorb Susp');
UPDATE public.products SET unit_price = 11.19, vetspire_product_id = '1067430', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Endosorb Tablets');
UPDATE public.products SET unit_price = 19.66, vetspire_product_id = '923212', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Enrofloxacin 136 mg tablets');
UPDATE public.products SET unit_price = 123.64, vetspire_product_id = '670551', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Entyce 30 mg/ml (15 ml)');
UPDATE public.products SET unit_price = 19.4, vetspire_product_id = '646635', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Epinephrine Inj 1 mg/ml');
UPDATE public.products SET unit_price = 69.89, vetspire_product_id = '646610', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Epiotic Advanced Ear Cleanser (8 oz)');
UPDATE public.products SET unit_price = 67.95, vetspire_product_id = '1069602', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Erythromycin 0.5% Ophthalmic Ointment (3.5 gm)');
UPDATE public.products SET unit_price = 35.12, vetspire_product_id = '670007', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('EZ Soft Collar - Small');
UPDATE public.products SET unit_price = 33.04, vetspire_product_id = '670006', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('EZ Soft Collar - XS');
UPDATE public.products SET unit_price = 10.7, vetspire_product_id = '981759', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Famotidine 10 mg tablets');
UPDATE public.products SET unit_price = 18.63, vetspire_product_id = '646636', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Famotidine Inj 10 mg/mL');
UPDATE public.products SET unit_price = 11.12, vetspire_product_id = '646519', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Fenbendazole Susp 100 mg/ml');
UPDATE public.products SET unit_price = 19.95, vetspire_product_id = '646637', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Flumazenil Inj  0.1 mg/ml');
UPDATE public.products SET unit_price = 11.05, vetspire_product_id = '646520', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Furosemide 12.5 mg tablets');
UPDATE public.products SET unit_price = 17.3, vetspire_product_id = '646638', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Furosemide Inj 50 mg/ml');
UPDATE public.products SET unit_price = 11.4, vetspire_product_id = '667659', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Furosemide Syrup 1% (10 mg/ml)');
UPDATE public.products SET unit_price = 10.49, vetspire_product_id = '646523', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Gabapentin 100 mg capsules');
UPDATE public.products SET unit_price = 14.2, vetspire_product_id = '868294', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Gabapentin 100 mg QuadTabs');
UPDATE public.products SET unit_price = 10.61, vetspire_product_id = '646524', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Gabapentin 300 mg capsules');
UPDATE public.products SET unit_price = 11.98, vetspire_product_id = '646525', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Gabapentin Solu 100 mg/ml');
UPDATE public.products SET unit_price = 10.08, vetspire_product_id = '649056', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Glycerin 99% U.S.P.  (1 Gallon)');
UPDATE public.products SET unit_price = 15.7, vetspire_product_id = '1933389', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Hill''s Canine Gastrointestinal Biome Chicken and Vegetable Stew (12.5oz)');
UPDATE public.products SET unit_price = 13.32, vetspire_product_id = '667670', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Hill''s c/d Feline Urinary Care (5.5 oz)');
UPDATE public.products SET unit_price = 12.69, vetspire_product_id = '1848212', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Hill''s Feline Gastrointestinal Biome (2.9 oz)');
UPDATE public.products SET unit_price = 15.19, vetspire_product_id = '646677', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Hill''s i/d Canine Low Fat Stew (12.5 oz)');
UPDATE public.products SET unit_price = 10.7, vetspire_product_id = '646458', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Hydrocodone 5 mg /Homatropine 1.5 mg Solu / 5ml');
UPDATE public.products SET unit_price = 28.35, vetspire_product_id = '837592', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Hydromorphone Inj 2 mg/ml');
UPDATE public.products SET unit_price = 14.52, vetspire_product_id = '646412', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Hypertonic Saline Inj 7.2%');
UPDATE public.products SET unit_price = 23.8, vetspire_product_id = '646616', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Ketamine HCl Inj 100 mg/ml');
UPDATE public.products SET unit_price = 10.21, vetspire_product_id = '646532', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Lactulose Solu 10 g/15 ml (32 oz)');
UPDATE public.products SET unit_price = 44.93, vetspire_product_id = '646592', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Latanoprost Ophthalmic Solu 0.005% (2.5 ml)');
UPDATE public.products SET unit_price = 11.12, vetspire_product_id = '646530', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Levetiracetam 750 mg tablets');
UPDATE public.products SET unit_price = 10.28, vetspire_product_id = '646529', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Levetiracetam Solu 100 mg/ml (16 oz)');
UPDATE public.products SET unit_price = 14.87, vetspire_product_id = '646644', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Lidocaine HCl 2% Inj (20 mg/ml)');
UPDATE public.products SET unit_price = 11.12, vetspire_product_id = '646531', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Lidocaine HCl 2%  Topical Solu (20 mg/ml)');
UPDATE public.products SET unit_price = 16.39, vetspire_product_id = '646413', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Mannitol 20% Inj (200 mg/ml)');
UPDATE public.products SET unit_price = 24.76, vetspire_product_id = '646538', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Maropitant 16 mg tablets');
UPDATE public.products SET unit_price = 25.2, vetspire_product_id = '646539', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Maropitant 24 mg tablets');
UPDATE public.products SET unit_price = 31.2, vetspire_product_id = '646540', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Maropitant 60 mg tablets');
UPDATE public.products SET unit_price = 65.25, vetspire_product_id = '2333592', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Maropitant Inj 10 mg/ml');
UPDATE public.products SET unit_price = 80.17, vetspire_product_id = '646542', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Meloxicam Susp 0.5 mg/ml');
UPDATE public.products SET unit_price = 1.75, vetspire_product_id = '1743626', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Metamucil (Psyllium Husk Fiber) / tsp');
UPDATE public.products SET unit_price = 161.29, vetspire_product_id = '646617', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Methadone Inj 10 mg/ml');
UPDATE public.products SET unit_price = 11.26, vetspire_product_id = '646543', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Methimazole 5 mg tablets');
UPDATE public.products SET unit_price = 10.84, vetspire_product_id = '646544', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Methocarbamol 500 mg tablets');
UPDATE public.products SET unit_price = 10.35, vetspire_product_id = '646545', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Metronidazole 250 mg tablets');
UPDATE public.products SET unit_price = 10.91, vetspire_product_id = '646546', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Metronidazole 500 mg tablets');
UPDATE public.products SET unit_price = 11.96, vetspire_product_id = '646548', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Metronidazole Benzoate Sus 100 mg/ml');
UPDATE public.products SET unit_price = 13.64, vetspire_product_id = '646547', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Metronidazole Tiny Tabs 50 mg  tablets');
UPDATE public.products SET unit_price = 55.0, vetspire_product_id = '523819', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Microchip Implantation');
UPDATE public.products SET unit_price = 18.3, vetspire_product_id = '646618', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Midazolam Inj 5 mg/ml');
UPDATE public.products SET unit_price = 16.5, vetspire_product_id = '1140862', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Mirtazapine 7.5 mg tablets');
UPDATE public.products SET unit_price = 93.61, vetspire_product_id = '646550', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Mirtazapine Transdermal Ointment 5 gm');
UPDATE public.products SET unit_price = 89.5, vetspire_product_id = '646604', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Mometamax Susp (15 gm)');
UPDATE public.products SET unit_price = 52.72, vetspire_product_id = '646647', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Naloxone Inj 0.4 mg/ml');
UPDATE public.products SET unit_price = 72.98, vetspire_product_id = '1069601', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('No Flap Ear Wrap - Large');
UPDATE public.products SET unit_price = 72.98, vetspire_product_id = '1069600', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('No Flap Ear Wrap - Medium');
UPDATE public.products SET unit_price = 72.98, vetspire_product_id = '1069598', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('No Flap Ear Wrap - Small');
UPDATE public.products SET unit_price = 52.98, vetspire_product_id = '1333328', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('NPD Ophthalmic Ointment (3.5g)');
UPDATE public.products SET unit_price = 62.01, vetspire_product_id = '646599', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('NPD Ophthalmic Susp (5 ml)');
UPDATE public.products SET unit_price = 69.2, vetspire_product_id = '646593', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Ofloxacin 0.3% Ophthalmic Solu (5 ml)');
UPDATE public.products SET unit_price = 182.5, vetspire_product_id = '646648', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Omnipaque (Iohexol) Inj 350 mg/ml');
UPDATE public.products SET unit_price = 10.98, vetspire_product_id = '646554', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Ondansetron 4 mg tablets');
UPDATE public.products SET unit_price = 11.4, vetspire_product_id = '771653', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Ondansetron 8 mg tablets');
UPDATE public.products SET unit_price = 16.81, vetspire_product_id = '646649', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Ondansetron Inj 2 mg/ml');
UPDATE public.products SET unit_price = 62.8, vetspire_product_id = '646594', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Optixcare PLUS Eye Lube (20 gm)');
UPDATE public.products SET unit_price = 32.43, vetspire_product_id = '646556', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Panacur C Canine 1 g (3/box)');
UPDATE public.products SET unit_price = 44.02, vetspire_product_id = '646557', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Panacur C Canine 2 g  (3/box)');
UPDATE public.products SET unit_price = 55.05, vetspire_product_id = '646558', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Panacur C Canine 4 g (3/box)');
UPDATE public.products SET unit_price = 17.1, vetspire_product_id = '646559', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Pimobendan 2.5 mg tablets');
UPDATE public.products SET unit_price = 106.57, vetspire_product_id = '646605', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Posatex Susp (15 gm)');
UPDATE public.products SET unit_price = 10.4, vetspire_product_id = '646566', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Prednisolone 5 mg tablets');
UPDATE public.products SET unit_price = 103.0, vetspire_product_id = '646596', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Prednisolone  Acetate 1% Opthalmic Susp (5 ml)');
UPDATE public.products SET unit_price = 11.19, vetspire_product_id = '646564', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Prednisolone Solu 15 mg/ 5 ml');
UPDATE public.products SET unit_price = 10.56, vetspire_product_id = '646568', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('PredniSONE 10 mg tablets');
UPDATE public.products SET unit_price = 10.56, vetspire_product_id = '646590', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Proparacaine 0.5% Opthalmic Solu (15 ml)');
UPDATE public.products SET unit_price = 60.7, vetspire_product_id = '646573', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Proviable Paste Kit  (Cat/Small Dog)');
UPDATE public.products SET unit_price = 66.7, vetspire_product_id = '646574', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Proviable Paste Kit (Medium/Large Dog)');
UPDATE public.products SET unit_price = 53.0, vetspire_product_id = '871643', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('PureVax 3 Feline RCP Vaccine');
UPDATE public.products SET unit_price = 79.0, vetspire_product_id = '646383', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('PureVax Feline Rabies Vaccine - 1 Year');
UPDATE public.products SET unit_price = 157.0, vetspire_product_id = '646384', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('PureVax Feline Rabies Vaccine - 3 Year');
UPDATE public.products SET unit_price = 53.0, vetspire_product_id = '646385', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('PureVax Recombinant FeLV Vaccine');
UPDATE public.products SET unit_price = 10.28, vetspire_product_id = '886431', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Pyrantel Pamoate (50 mg/ml)');
UPDATE public.products SET unit_price = 6.0, vetspire_product_id = '680801', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Rabies Tag - 1 Year');
UPDATE public.products SET unit_price = 18.0, vetspire_product_id = '680803', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Rabies Tag - 3 Year');
UPDATE public.products SET unit_price = 61.0, vetspire_product_id = '646676', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Revolution PLUS Topical 11.1 to 22 lbs');
UPDATE public.products SET unit_price = 53.59, vetspire_product_id = '646674', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Revolution PLUS Topical 2.8 to 5.5 lbs');
UPDATE public.products SET unit_price = 59.74, vetspire_product_id = '646675', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Revolution PLUS Topical 5.6 to 11 lbs');
UPDATE public.products SET unit_price = 59.35, vetspire_product_id = '886430', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Revolution Puppies & Kittens < 5 lbs');
UPDATE public.products SET unit_price = 56.95, vetspire_product_id = '646576', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Robenacoxib 6 mg tablets (3/box)');
UPDATE public.products SET unit_price = 12.85, vetspire_product_id = '646680', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Royal Canin Feline SO (5.1 oz)');
UPDATE public.products SET unit_price = 103.0, vetspire_product_id = '628229', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('SNAP 4DX Plus Test');
UPDATE public.products SET unit_price = 99.5, vetspire_product_id = '628237', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('SNAP Feline proBNP Test');
UPDATE public.products SET unit_price = 112.0, vetspire_product_id = '628234', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('SNAP Feline Triple Test');
UPDATE public.products SET unit_price = 106.5, vetspire_product_id = '628233', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('SNAP Parvo Test');
UPDATE public.products SET unit_price = 152.74, vetspire_product_id = '873304', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Solensia');
UPDATE public.products SET unit_price = 177.8, vetspire_product_id = '2148179', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Solovecin (Cefovecin Sodium) Inj 80 mg/ml');
UPDATE public.products SET unit_price = 11.61, vetspire_product_id = '1743750', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Sucralfate 1 gm tablets');
UPDATE public.products SET unit_price = 86.62, vetspire_product_id = '646595', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Terramycin (Oxytetracycline Hydrochloride) Opthalmic Ointment  (3.5 gm)');
UPDATE public.products SET unit_price = 59.7, vetspire_product_id = '646597', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Tobramycin 0.3% Ophthalmic Solu (5 ml)');
UPDATE public.products SET unit_price = 10.5, vetspire_product_id = '646579', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('ToxiBan (without Sorbitol)');
UPDATE public.products SET unit_price = 10.56, vetspire_product_id = '646580', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Trazodone 100 mg tablets');
UPDATE public.products SET unit_price = 10.49, vetspire_product_id = '646581', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Trazodone 50 mg tablets');
UPDATE public.products SET unit_price = 48.67, vetspire_product_id = '1069603', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('TrizEDTA Aqueous Otic Flush (4 oz)');
UPDATE public.products SET unit_price = 75.7, vetspire_product_id = '646608', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('TrizULTRA + KETO Otic Flush (12 oz)');
UPDATE public.products SET unit_price = 15.5, vetspire_product_id = '628242', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('UA Strip');
UPDATE public.products SET unit_price = 41.5, vetspire_product_id = '628426', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Urine Drug Screen');
UPDATE public.products SET unit_price = 53.0, vetspire_product_id = '646376', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Vanguard Bordetella Vaccine Oral SF');
UPDATE public.products SET unit_price = 69.0, vetspire_product_id = '646377', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Vanguard CIV Vaccine (H3N2 & H3N8)');
UPDATE public.products SET unit_price = 69.0, vetspire_product_id = '646378', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Vanguard crLyme Vaccine');
UPDATE public.products SET unit_price = 62.0, vetspire_product_id = '646379', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Vanguard DAPP + L4 Vaccine');
UPDATE public.products SET unit_price = 50.0, vetspire_product_id = '646380', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Vanguard DAPP Vaccine');
UPDATE public.products SET unit_price = 53.0, vetspire_product_id = '646381', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Vanguard L4 Lepto Vaccine');
UPDATE public.products SET unit_price = 59.0, vetspire_product_id = '646374', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Vanguard Rabies Vaccine - 1 Year');
UPDATE public.products SET unit_price = 95.0, vetspire_product_id = '646373', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Vanguard Rabies Vaccine - 3 Year');
UPDATE public.products SET unit_price = 96.85, vetspire_product_id = '646584', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Veraflox Susp 25 mg/ml (15 ml bottle)');
UPDATE public.products SET unit_price = 11.19, vetspire_product_id = '837585', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Viralys Powder');
UPDATE public.products SET unit_price = 12.94, vetspire_product_id = '646585', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Vitamin K-1 50 mg tablets');
UPDATE public.products SET unit_price = 61.21, vetspire_product_id = '646587', price_year = '2026' WHERE vetspire_product_id IS NULL AND lower(trim(name)) = lower('Yunnan Baiyao (16/box)');

COMMIT;

-- Verification
SELECT count(*) AS mapped FROM public.products WHERE vetspire_product_id IS NOT NULL;
SELECT count(*) AS with_price FROM public.products WHERE unit_price IS NOT NULL;
