-- Auto-generated: update products with dispensing_unit and package_size
-- Review before running in Supabase SQL Editor.

UPDATE products SET dispensing_unit = 'tablets', package_size = 500.0 WHERE name = 'Albon (Sulfadimethoxine) 250 mg tablets';
UPDATE products SET dispensing_unit = 'can', package_size = 1.0 WHERE name = 'Albuterol HFA 90 mcg';
UPDATE products SET dispensing_unit = 'mL', package_size = 20.0 WHERE name = 'Alfaxalone Inj 10 mg/ml';
UPDATE products SET dispensing_unit = 'mL', package_size = 473.0 WHERE name = 'Aluminum Hydroxide 64 mg/ml solution';
UPDATE products SET dispensing_unit = 'tablets', package_size = 90.0 WHERE name = 'Amlodipine 2.5 mg tablets';
UPDATE products SET dispensing_unit = 'vials', package_size = 10.0 WHERE name = 'Amp+Sulbactam Inj 30 mg/ml (1.5 g vial)';
UPDATE products SET dispensing_unit = 'tube', package_size = 1.0 WHERE name = 'Animax Ointment (15 ml)';
UPDATE products SET dispensing_unit = 'mL', package_size = 10.0 WHERE name = 'Apomorphine HCl 3 mg/ml';
UPDATE products SET dispensing_unit = 'tablets', package_size = 250.0 WHERE name = 'Apoquel 16 mg tablets';
UPDATE products SET dispensing_unit = 'tablets', package_size = 250.0 WHERE name = 'Apoquel 3.6 mg tablets';
UPDATE products SET dispensing_unit = 'tablets', package_size = 250.0 WHERE name = 'Apoquel 5.4 mg tablets';
UPDATE products SET dispensing_unit = 'mL', package_size = 10.0 WHERE name = 'Atipamezole HCl  Inj 5 mg/ml';
UPDATE products SET dispensing_unit = 'mL', package_size = 100.0 WHERE name = 'Atropine Inj 0.54 mg/ml';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Aural Hematoma - Teat Cannula';
UPDATE products SET dispensing_unit = 'bottles', package_size = 12.0 WHERE name = 'Baytril Otic (15 ml)';
UPDATE products SET dispensing_unit = 'tube', package_size = 1.0 WHERE name = 'BNP Opthalmic Ointment (3.5 gm)';
UPDATE products SET dispensing_unit = 'mL', package_size = 1.0 WHERE name = 'Buprenorphine  Inj 0.3 mg/ml';
UPDATE products SET dispensing_unit = 'mL', package_size = 50.0 WHERE name = 'Butorphanol Inj 10 mg/ml';
UPDATE products SET dispensing_unit = 'mL', package_size = 10.0 WHERE name = 'Calcium Gluconate 10% Inj (100 mg/ml)';
UPDATE products SET dispensing_unit = 'tablets', package_size = 6.0 WHERE name = 'Capstar Tablet 11.4 mg (Cats  and Small  Dogs 2 to 25 lbs)';
UPDATE products SET dispensing_unit = 'tablets', package_size = 180.0 WHERE name = 'Carprofen 100 mg tablets';
UPDATE products SET dispensing_unit = 'tablets', package_size = 180.0 WHERE name = 'Carprofen 25 mg tablets';
UPDATE products SET dispensing_unit = 'tablets', package_size = 180.0 WHERE name = 'Carprofen 75 mg tablets';
UPDATE products SET dispensing_unit = 'rolls', package_size = 10.0 WHERE name = 'Cast - Vetcast 2in';
UPDATE products SET dispensing_unit = 'rolls', package_size = 10.0 WHERE name = 'Cast - Vetcast 3in';
UPDATE products SET dispensing_unit = 'rolls', package_size = 10.0 WHERE name = 'Cast - Vetcast 4in';
UPDATE products SET dispensing_unit = 'clips', package_size = 12.0 WHERE name = 'Catalyst Alkaline Aminotransferase (ALT)';
UPDATE products SET dispensing_unit = 'clips', package_size = 12.0 WHERE name = 'Catalyst Alkaline Phosphatase (ALP)';
UPDATE products SET dispensing_unit = 'clips', package_size = 12.0 WHERE name = 'Catalyst Ammonia (NH3)';
UPDATE products SET dispensing_unit = 'clips', package_size = 12.0 WHERE name = 'Catalyst Blood Urea Nitrogen (BUN)';
UPDATE products SET dispensing_unit = 'clips', package_size = 12.0 WHERE name = 'Catalyst Chem 10';
UPDATE products SET dispensing_unit = 'clips', package_size = 12.0 WHERE name = 'Catalyst Chem 17';
UPDATE products SET dispensing_unit = 'tests', package_size = 6.0 WHERE name = 'Catalyst Cortisol';
UPDATE products SET dispensing_unit = 'clips', package_size = 12.0 WHERE name = 'Catalyst Creatinine (CREA)';
UPDATE products SET dispensing_unit = 'tests', package_size = 6.0 WHERE name = 'Catalyst Fructosamine (FRU)';
UPDATE products SET dispensing_unit = 'clips', package_size = 12.0 WHERE name = 'Catalyst Inorganic Phosphate (PHOS)';
UPDATE products SET dispensing_unit = 'clips', package_size = 12.0 WHERE name = 'Catalyst Lactate (LAC)';
UPDATE products SET dispensing_unit = 'clips', package_size = 12.0 WHERE name = 'Catalyst Lytes 4';
UPDATE products SET dispensing_unit = 'clips', package_size = 12.0 WHERE name = 'Catalyst NSAID 6';
UPDATE products SET dispensing_unit = 'tests', package_size = 12.0 WHERE name = 'Catalyst Pancreatic Lipase  (PL)';
UPDATE products SET dispensing_unit = 'clips', package_size = 12.0 WHERE name = 'Catalyst Total Bilirubin (TBILI)';
UPDATE products SET dispensing_unit = 'tests', package_size = 12.0 WHERE name = 'Catalyst Total T4 (TT4)';
UPDATE products SET dispensing_unit = 'tablets', package_size = 100.0 WHERE name = 'Cefpodoxime 200 mg tablets';
UPDATE products SET dispensing_unit = 'capsules', package_size = 500.0 WHERE name = 'Cephalexin 250 mg capsules';
UPDATE products SET dispensing_unit = 'capsules', package_size = 500.0 WHERE name = 'Cephalexin 500 mg capsules';
UPDATE products SET dispensing_unit = 'tubes', package_size = 10.0 WHERE name = 'Claro Otic (1 ml)';
UPDATE products SET dispensing_unit = 'mL', package_size = 15.0 WHERE name = 'Clavacillin  Susp 62.5 mg/ml (15 ml bottle)';
UPDATE products SET dispensing_unit = 'tablets', package_size = 210.0 WHERE name = 'Clavacillin 125 mg tablets';
UPDATE products SET dispensing_unit = 'tablets', package_size = 210.0 WHERE name = 'Clavacillin 250 mg tablets';
UPDATE products SET dispensing_unit = 'tablets', package_size = 210.0 WHERE name = 'Clavacillin 375 mg tablets';
UPDATE products SET dispensing_unit = 'tablets', package_size = 210.0 WHERE name = 'Clavacillin 62.5 mg tablets';
UPDATE products SET dispensing_unit = 'capsules', package_size = 500.0 WHERE name = 'Clindamycin 150 mg capsules';
UPDATE products SET dispensing_unit = 'mL', package_size = 20.0 WHERE name = 'Clindamycin Susp 25 mg/ml (20 ml bottle)';
UPDATE products SET dispensing_unit = 'tests', package_size = 10.0 WHERE name = 'Coag Dx Citrate Activated Partial Thromboplastin Time (aPTT)';
UPDATE products SET dispensing_unit = 'tests', package_size = 10.0 WHERE name = 'Coag Dx Citrate Prothrombin Time (PT)';
UPDATE products SET dispensing_unit = 'mL', package_size = 10.0 WHERE name = 'Convenia (Cefovecin Sodium) Inj 80 mg/ml';
UPDATE products SET dispensing_unit = 'vial', package_size = 1.0 WHERE name = 'Cytopoint 10 mg (1 ml vial)';
UPDATE products SET dispensing_unit = 'vial', package_size = 1.0 WHERE name = 'Cytopoint 20 mg (1 ml vial)';
UPDATE products SET dispensing_unit = 'vial', package_size = 1.0 WHERE name = 'Cytopoint 30 mg (1 ml vial)';
UPDATE products SET dispensing_unit = 'vial', package_size = 1.0 WHERE name = 'Cytopoint 40 mg (1 ml vial)';
UPDATE products SET dispensing_unit = 'mL', package_size = 1.0 WHERE name = 'Dexamethasone-SP Inj 4 mg/ml';
UPDATE products SET dispensing_unit = 'mL', package_size = 10.0 WHERE name = 'Dexmedetomidine Inj 0.5 mg/ml';
UPDATE products SET dispensing_unit = 'mL', package_size = 500.0 WHERE name = 'Dextrose Solu Inj 50%';
UPDATE products SET dispensing_unit = 'capsules', package_size = 100.0 WHERE name = 'Diphenhydramine 25 mg capsules';
UPDATE products SET dispensing_unit = 'capsules', package_size = 100.0 WHERE name = 'Diphenhydramine 50 mg capsules';
UPDATE products SET dispensing_unit = 'mL', package_size = 10.0 WHERE name = 'Diphenhydramine Inj 50 mg/ml';
UPDATE products SET dispensing_unit = 'mL', package_size = 120.0 WHERE name = 'Diphenhydramine Syrup 12.5 mg/5 ml';
UPDATE products SET dispensing_unit = 'bottle', package_size = 1.0 WHERE name = 'Dorzolamide Timolol 2-0.5% Solu (10 ml)';
UPDATE products SET dispensing_unit = 'bottle', package_size = 1.0 WHERE name = 'Douxo S3 PYO Mousse (5.1 oz)';
UPDATE products SET dispensing_unit = 'bottle', package_size = 1.0 WHERE name = 'Douxo S3 PYO Shampoo (6.7 oz)';
UPDATE products SET dispensing_unit = 'wipes', package_size = 30.0 WHERE name = 'Douxo S3 PYO Wipes (30 ct)';
UPDATE products SET dispensing_unit = 'capsules', package_size = 500.0 WHERE name = 'Doxycycline 100 mg capsules';
UPDATE products SET dispensing_unit = 'tablets', package_size = 500.0 WHERE name = 'Doxycycline 100 mg tablets';
UPDATE products SET dispensing_unit = 'mL', package_size = 120.0 WHERE name = 'Doxycycline Solu 100 mg/ml';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Drain - Continuous Suction Bulb 100 ml';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Drain - Jackson Pratt 10fr';
UPDATE products SET dispensing_unit = 'each', package_size = 10.0 WHERE name = 'Drain - Penrose 1/4 in x 18 in';
UPDATE products SET dispensing_unit = 'tablets', package_size = 50.0 WHERE name = 'Drontal (Praziquantel/Pyrantel Pamoate) for Cats and Kittens';
UPDATE products SET dispensing_unit = 'tablets', package_size = 30.0 WHERE name = 'Drontal (Praziquantel/Pyrantel Pamoate/Febantel) PLUS for Large Dogs';
UPDATE products SET dispensing_unit = 'tablets', package_size = 50.0 WHERE name = 'Drontal (Praziquantel/Pyrantel Pamoate/Febantel) PLUS for Medium Dogs';
UPDATE products SET dispensing_unit = 'tablets', package_size = 50.0 WHERE name = 'Drontal (Praziquantel/Pyrantel Pamoate/Febantel) PLUS for Puppies & Small Dogs';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'E-Collar - 10 cm';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'E-Collar - 12 cm';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'E-Collar - 15 cm';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'E-Collar - 20 cm';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'E-Collar - 25 cm';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'E-Collar - 30 cm';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'E-Collar - 7.5 cm';
UPDATE products SET dispensing_unit = 'mL', package_size = 15.0 WHERE name = 'Elura 20 mg/ml (15 ml)';
UPDATE products SET dispensing_unit = 'mL', package_size = 120.0 WHERE name = 'Endosorb Susp';
UPDATE products SET dispensing_unit = 'tablets', package_size = 500.0 WHERE name = 'Endosorb Tablets';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Endotracheal Tube - 10 mm Cuffed';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Endotracheal Tube - 10.5 mm Cuffed';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Endotracheal Tube - 11.0 mm Cuffed';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Endotracheal Tube - 3.0 mm Cuffed';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Endotracheal Tube - 3.5 mm Cuffed';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Endotracheal Tube - 4.0 mm Cuffed';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Endotracheal Tube - 4.5 mm Cuffed';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Endotracheal Tube - 5.0 mm Cuffed';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Endotracheal Tube - 5.5 mm Cuffed';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Endotracheal Tube - 6.0 mm Cuffed';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Endotracheal Tube - 6.5 mm Cuffed';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Endotracheal Tube - 7.0 mm Cuffed';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Endotracheal Tube - 7.5 mm Cuffed';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Endotracheal Tube - 8.0 mm Cuffed';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Endotracheal Tube - 8.5 mm Cuffed';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Endotracheal Tube - 9.0 mm Cuffed';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Endotracheal Tube - 9.5 mm Cuffed';
UPDATE products SET dispensing_unit = 'tablets', package_size = 50.0 WHERE name = 'Enrofloxacin 136 mg tablets';
UPDATE products SET dispensing_unit = 'mL', package_size = 15.0 WHERE name = 'Entyce 30 mg/ml (15 ml)';
UPDATE products SET dispensing_unit = 'bottle', package_size = 1.0 WHERE name = 'Epi-Otic Advanced Ear Cleanser (8 oz)';
UPDATE products SET dispensing_unit = 'mL', package_size = 50.0 WHERE name = 'Epinephrine Inj 1 mg/ml';
UPDATE products SET dispensing_unit = 'tube', package_size = 1.0 WHERE name = 'Erythromycin 0.5% Ophthalmic Ointment (3.5 gm)';
UPDATE products SET dispensing_unit = 'mL', package_size = 100.0 WHERE name = 'Euthasol';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'EZ Soft Collar - Small';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'EZ Soft Collar - XS';
UPDATE products SET dispensing_unit = 'tablets', package_size = 30.0 WHERE name = 'Famotidine 10 mg tablets';
UPDATE products SET dispensing_unit = 'mL', package_size = 20.0 WHERE name = 'Famotidine Inj 10 mg/mL';
UPDATE products SET dispensing_unit = 'mL', package_size = 1000.0 WHERE name = 'Fenbendazole Susp 100 mg/ml';
UPDATE products SET dispensing_unit = 'mL', package_size = 5.0 WHERE name = 'Flumazenil Inj  0.1 mg/ml';
UPDATE products SET dispensing_unit = 'strips', package_size = 100.0 WHERE name = 'Fluorescein I-Glo Test Strip';
UPDATE products SET dispensing_unit = 'tablets', package_size = 500.0 WHERE name = 'Furosemide 12.5 mg tablets';
UPDATE products SET dispensing_unit = 'mL', package_size = 50.0 WHERE name = 'Furosemide Inj 50 mg/ml';
UPDATE products SET dispensing_unit = 'mL', package_size = 60.0 WHERE name = 'Furosemide Syrup 1% (10 mg/ml)';
UPDATE products SET dispensing_unit = 'capsules', package_size = 500.0 WHERE name = 'Gabapentin 100 mg capsules';
UPDATE products SET dispensing_unit = 'tablets', package_size = 30.0 WHERE name = 'Gabapentin 100 mg QuadTabs';
UPDATE products SET dispensing_unit = 'capsules', package_size = 500.0 WHERE name = 'Gabapentin 300 mg capsules';
UPDATE products SET dispensing_unit = 'mL', package_size = 480.0 WHERE name = 'Gabapentin Solu 100 mg/ml';
UPDATE products SET dispensing_unit = 'mL', package_size = 3785.0 WHERE name = 'Glycerin 99% U.S.P.  (1 Gallon)';
UPDATE products SET dispensing_unit = 'cans', package_size = 24.0 WHERE name = 'Hill''s c/d Feline Urinary Care (5.5 oz)';
UPDATE products SET dispensing_unit = 'cans', package_size = 12.0 WHERE name = 'Hill''s Canine Gastrointestinal Biome Chicken and Vegetable Stew (12.5oz)';
UPDATE products SET dispensing_unit = 'cans', package_size = 12.0 WHERE name = 'Hill''s Feline Gastrointestinal Biome (2.9 oz)';
UPDATE products SET dispensing_unit = 'cans', package_size = 12.0 WHERE name = 'Hill''s i/d Canine Chicken and Vegetable Stew (12.5 oz)';
UPDATE products SET dispensing_unit = 'cans', package_size = 12.0 WHERE name = 'Hill''s i/d Canine Low Fat Stew (12.5 oz)';
UPDATE products SET dispensing_unit = 'cans', package_size = 24.0 WHERE name = 'Hill''s i/d Feline (5.5 oz)';
UPDATE products SET dispensing_unit = 'mL', package_size = 473.0 WHERE name = 'Hydrocodone 5 mg /Homatropine 1.5 mg Solu / 5ml';
UPDATE products SET dispensing_unit = 'mL', package_size = 20.0 WHERE name = 'Hydromorphone Inj 2 mg/ml';
UPDATE products SET dispensing_unit = 'mL', package_size = 1000.0 WHERE name = 'Hypertonic Saline Inj 7.2%';
UPDATE products SET dispensing_unit = 'mL', package_size = 10.0 WHERE name = 'Ketamine HCl Inj 100 mg/ml';
UPDATE products SET dispensing_unit = 'mL', package_size = 946.0 WHERE name = 'Lactulose Solu 10 g/15 ml (32 oz)';
UPDATE products SET dispensing_unit = 'bottle', package_size = 1.0 WHERE name = 'Latanoprost Ophthalmic Solu 0.005% (2.5 ml)';
UPDATE products SET dispensing_unit = 'tablets', package_size = 120.0 WHERE name = 'Levetiracetam 250 mg tablets';
UPDATE products SET dispensing_unit = 'tablets', package_size = 120.0 WHERE name = 'Levetiracetam 750 mg tablets';
UPDATE products SET dispensing_unit = 'mL', package_size = 473.0 WHERE name = 'Levetiracetam Solu 100 mg/ml (16 oz)';
UPDATE products SET dispensing_unit = 'mL', package_size = 100.0 WHERE name = 'Lidocaine HCl 2%  Oral Solu (20 mg/ml)';
UPDATE products SET dispensing_unit = 'mL', package_size = 100.0 WHERE name = 'Lidocaine HCl 2% Inj (20 mg/ml)';
UPDATE products SET dispensing_unit = 'mL', package_size = 100.0 WHERE name = 'Mannitol 20% Inj (200 mg/ml)';
UPDATE products SET dispensing_unit = 'tablets', package_size = 4.0 WHERE name = 'Maropitant 16 mg tablets';
UPDATE products SET dispensing_unit = 'tablets', package_size = 4.0 WHERE name = 'Maropitant 24 mg tablets';
UPDATE products SET dispensing_unit = 'tablets', package_size = 4.0 WHERE name = 'Maropitant 60 mg tablets';
UPDATE products SET dispensing_unit = 'mL', package_size = 20.0 WHERE name = 'Maropitant Inj 10 mg/ml';
UPDATE products SET dispensing_unit = 'mL', package_size = 15.0 WHERE name = 'Meloxicam Susp 0.5 mg/ml';
UPDATE products SET dispensing_unit = 'canister', package_size = 1.0 WHERE name = 'Metamucil (Psyllium Husk Fiber) / tsp';
UPDATE products SET dispensing_unit = 'mL', package_size = 20.0 WHERE name = 'Methadone Inj 10 mg/ml';
UPDATE products SET dispensing_unit = 'tablets', package_size = 100.0 WHERE name = 'Methimazole 5 mg tablets';
UPDATE products SET dispensing_unit = 'tablets', package_size = 100.0 WHERE name = 'Methocarbamol 500 mg tablets';
UPDATE products SET dispensing_unit = 'tablets', package_size = 500.0 WHERE name = 'Metronidazole 250 mg tablets';
UPDATE products SET dispensing_unit = 'tablets', package_size = 500.0 WHERE name = 'Metronidazole 500 mg tablets';
UPDATE products SET dispensing_unit = 'mL', package_size = 460.0 WHERE name = 'Metronidazole Benzoate Sus 100 mg/ml';
UPDATE products SET dispensing_unit = 'tablets', package_size = 100.0 WHERE name = 'Metronidazole Tiny Tabs 50 mg  tablets';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Microchip';
UPDATE products SET dispensing_unit = 'mL', package_size = 10.0 WHERE name = 'Midazolam Inj 5 mg/ml';
UPDATE products SET dispensing_unit = 'tablets', package_size = 30.0 WHERE name = 'Mirtazapine 7.5mg tablets';
UPDATE products SET dispensing_unit = 'tube', package_size = 1.0 WHERE name = 'Mirtazapine Transdermal Ointment 5 gm';
UPDATE products SET dispensing_unit = 'bottles', package_size = 12.0 WHERE name = 'Mometamax Susp (15 gm)';
UPDATE products SET dispensing_unit = 'mL', package_size = 10.0 WHERE name = 'Naloxone Inj 0.4 mg/ml';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Nasogastric Tube - 10fr x 90 cm';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Nasogastric Tube - 5fr x 55 cm MILA';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Nasogastric Tube - 6fr x 55 cm MILA';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Nasogastric Tube - 8fr x 90 cm MILA';
UPDATE products SET dispensing_unit = 'tube', package_size = 1.0 WHERE name = 'Nitro-Bid Ointment 2%';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'No Flap Ear Wrap - Large';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'No Flap Ear Wrap - Medium';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'No Flap Ear Wrap - Small';
UPDATE products SET dispensing_unit = 'tube', package_size = 1.0 WHERE name = 'NPD Ophthalmic Ointment (3.5g)';
UPDATE products SET dispensing_unit = 'bottle', package_size = 1.0 WHERE name = 'NPD Ophthalmic Susp (5 ml)';
UPDATE products SET dispensing_unit = 'bottle', package_size = 1.0 WHERE name = 'Ofloxacin 0.3% Ophthalmic Solu (5 ml)';
UPDATE products SET dispensing_unit = 'mL', package_size = 100.0 WHERE name = 'Omnipaque (Iohexol) Inj 350 mg/ml';
UPDATE products SET dispensing_unit = 'tablets', package_size = 30.0 WHERE name = 'Ondansetron 4 mg tablets';
UPDATE products SET dispensing_unit = 'tablets', package_size = 30.0 WHERE name = 'Ondansetron 8 mg tablets';
UPDATE products SET dispensing_unit = 'mL', package_size = 20.0 WHERE name = 'Ondansetron Inj 2 mg/ml';
UPDATE products SET dispensing_unit = 'tube', package_size = 1.0 WHERE name = 'Optixcare PLUS Eye Lube (20 gm)';
UPDATE products SET dispensing_unit = 'packets', package_size = 3.0 WHERE name = 'Panacur C Canine 1 g (3/box)';
UPDATE products SET dispensing_unit = 'packets', package_size = 3.0 WHERE name = 'Panacur C Canine 2 g  (3/box)';
UPDATE products SET dispensing_unit = 'packets', package_size = 3.0 WHERE name = 'Panacur C Canine 4 g (3/box)';
UPDATE products SET dispensing_unit = 'tablets', package_size = 50.0 WHERE name = 'Pimobendan 2.5 mg tablets';
UPDATE products SET dispensing_unit = 'bottles', package_size = 12.0 WHERE name = 'Posatex Susp (15 gm)';
UPDATE products SET dispensing_unit = 'tablets', package_size = 100.0 WHERE name = 'Prazosin Tiny Tabs 0.5 mg';
UPDATE products SET dispensing_unit = 'bottle', package_size = 1.0 WHERE name = 'Prednisolone  Acetate 1% Opthalmic Susp (5 ml)';
UPDATE products SET dispensing_unit = 'tablets', package_size = 1000.0 WHERE name = 'Prednisolone 5 mg tablets';
UPDATE products SET dispensing_unit = 'mL', package_size = 237.0 WHERE name = 'Prednisolone Solu 15 mg/ 5 ml';
UPDATE products SET dispensing_unit = 'tablets', package_size = 100.0 WHERE name = 'PredniSONE 10 mg tablets';
UPDATE products SET dispensing_unit = 'kit', package_size = 1.0 WHERE name = 'Procyte Dx Reagent Kit';
UPDATE products SET dispensing_unit = 'kit', package_size = 1.0 WHERE name = 'Procyte Quality Control e-CHECK';
UPDATE products SET dispensing_unit = 'bottle', package_size = 1.0 WHERE name = 'Proparacaine 0.5% Opthalmic Solu (15 ml)';
UPDATE products SET dispensing_unit = 'kit', package_size = 1.0 WHERE name = 'Proviable Paste Kit  (Cat/Small Dog)';
UPDATE products SET dispensing_unit = 'kit', package_size = 1.0 WHERE name = 'Proviable Paste Kit (Medium/Large Dog)';
UPDATE products SET dispensing_unit = 'doses', package_size = 25.0 WHERE name = 'PureVax 3 Feline RCP Vaccine';
UPDATE products SET dispensing_unit = 'doses', package_size = 25.0 WHERE name = 'PureVax Feline Rabies Vaccine - 1 Year';
UPDATE products SET dispensing_unit = 'doses', package_size = 25.0 WHERE name = 'PureVax Feline Rabies Vaccine - 3 Year';
UPDATE products SET dispensing_unit = 'doses', package_size = 25.0 WHERE name = 'PureVax Recombinant FeLV Vaccine';
UPDATE products SET dispensing_unit = 'mL', package_size = 473.0 WHERE name = 'Pyrantel Pamoate (50 mg/ml)';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Rabies Tag - 1 year';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Red Rubber - 10fr x 16in';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Red Rubber - 3.5fr x 16in';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Red Rubber - 5fr x 16in';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Red Rubber - 8fr x 22in';
UPDATE products SET dispensing_unit = 'tubes', package_size = 6.0 WHERE name = 'Revolution PLUS Topical 11.1 to 22 lbs';
UPDATE products SET dispensing_unit = 'tubes', package_size = 6.0 WHERE name = 'Revolution PLUS Topical 2.8 to 5.5 lbs';
UPDATE products SET dispensing_unit = 'tubes', package_size = 6.0 WHERE name = 'Revolution PLUS Topical 5.6 to 11 lbs';
UPDATE products SET dispensing_unit = 'tubes', package_size = 3.0 WHERE name = 'Revolution Puppies & Kittens < 5 lbs';
UPDATE products SET dispensing_unit = 'tablets', package_size = 3.0 WHERE name = 'Robenacoxib 6 mg tablets (3/box)';
UPDATE products SET dispensing_unit = 'cans', package_size = 24.0 WHERE name = 'Royal Canin Feline SO (5.1 oz)';
UPDATE products SET dispensing_unit = 'strips', package_size = 50.0 WHERE name = 'Schirmer Tear Test';
UPDATE products SET dispensing_unit = 'tests', package_size = 30.0 WHERE name = 'SNAP 4DX Plus Test';
UPDATE products SET dispensing_unit = 'tests', package_size = 5.0 WHERE name = 'SNAP Feline proBNP Test';
UPDATE products SET dispensing_unit = 'tests', package_size = 15.0 WHERE name = 'SNAP Feline Triple Test';
UPDATE products SET dispensing_unit = 'tests', package_size = 10.0 WHERE name = 'SNAP fPL Test';
UPDATE products SET dispensing_unit = 'tests', package_size = 5.0 WHERE name = 'SNAP Parvo Test';
UPDATE products SET dispensing_unit = 'vials', package_size = 6.0 WHERE name = 'Solensia';
UPDATE products SET dispensing_unit = 'mL', package_size = 10.0 WHERE name = 'Solovecin (Cefovecin Sodium) Injectable 80mg/ml';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Splint - Quick Splint (Large LFL/RFL)';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Splint - Quick Splint (Large LHL/RHL)';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Splint - Quick Splint (Medium LFL/RFL)';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Splint - Quick Splint (Medium LHL/RHL)';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Splint - Quick Splint (Small LFL/RFL)';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Splint - Quick Splint (Small LHL/RHL)';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Splint - Spoon Splint (Large)';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Splint - Spoon Splint (Medium)';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Splint - Spoon Splint (Small)';
UPDATE products SET dispensing_unit = 'tablets', package_size = 100.0 WHERE name = 'Sucralfate 1 gm tablets';
UPDATE products SET dispensing_unit = 'tube', package_size = 1.0 WHERE name = 'Terramycin (Oxytetracycline Hydrochloride) Opthalmic Ointment  (3.5 gm)';
UPDATE products SET dispensing_unit = 'bottle', package_size = 1.0 WHERE name = 'Tobramycin 0.3% Ophthalmic Solu (5 ml)';
UPDATE products SET dispensing_unit = 'mL', package_size = 240.0 WHERE name = 'ToxiBan (without Sorbitol)';
UPDATE products SET dispensing_unit = 'tablets', package_size = 100.0 WHERE name = 'Trazodone 100 mg tablets';
UPDATE products SET dispensing_unit = 'tablets', package_size = 100.0 WHERE name = 'Trazodone 50 mg tablets';
UPDATE products SET dispensing_unit = 'bottle', package_size = 1.0 WHERE name = 'TrizEDTA Aqueous Otic Flush (4 oz)';
UPDATE products SET dispensing_unit = 'bottle', package_size = 1.0 WHERE name = 'TrizULTRA + KETO Otic Flush (12 oz)';
UPDATE products SET dispensing_unit = 'box', package_size = 1.0 WHERE name = 'UA Strip';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Urinary Catheter - Foley 10fr x 90 cm w/ stylet';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Urinary Catheter - Foley 6fr x 60 cm w/ stylet';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Urinary Catheter - Foley 8fr x 60 cm w/ stylet';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Urinary Catheter - Slippery Sam Tomcat 3.5fr x 5in Closed End';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Urinary Catheter - Slippery Sam Tomcat 3.5fr x 6in Closed End';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Urine Collection Kit 1000 ml';
UPDATE products SET dispensing_unit = 'each', package_size = 1.0 WHERE name = 'Urine Drug Screen';
UPDATE products SET dispensing_unit = 'doses', package_size = 25.0 WHERE name = 'Vanguard Bordetella Oral SF';
UPDATE products SET dispensing_unit = 'doses', package_size = 25.0 WHERE name = 'Vanguard CIV (H3N2 & H3N8)';
UPDATE products SET dispensing_unit = 'doses', package_size = 25.0 WHERE name = 'Vanguard crLyme Vaccine';
UPDATE products SET dispensing_unit = 'doses', package_size = 25.0 WHERE name = 'Vanguard DAPP + L4 Vaccine';
UPDATE products SET dispensing_unit = 'doses', package_size = 25.0 WHERE name = 'Vanguard DAPP Vaccine';
UPDATE products SET dispensing_unit = 'doses', package_size = 25.0 WHERE name = 'Vanguard L4 Lepto Vaccine';
UPDATE products SET dispensing_unit = 'doses', package_size = 50.0 WHERE name = 'Vanguard Rabies Vaccine - 1 Year';
UPDATE products SET dispensing_unit = 'doses', package_size = 50.0 WHERE name = 'Vanguard Rabies Vaccine - 3 Year';
UPDATE products SET dispensing_unit = 'bottles', package_size = 6.0 WHERE name = 'Veraflox Susp 25 mg/ml (15 ml bottle)';
UPDATE products SET dispensing_unit = 'jar', package_size = 1.0 WHERE name = 'Viralys Powder';
UPDATE products SET dispensing_unit = 'tablets', package_size = 50.0 WHERE name = 'Vitamin K-1 50 mg tablets';
UPDATE products SET dispensing_unit = 'capsules', package_size = 16.0 WHERE name = 'Yunnan Baiyao (16/box)';
UPDATE products SET dispensing_unit = 'mL', package_size = 10.0 WHERE name = 'Zenalpha 0.5 mg/ml';
UPDATE products SET dispensing_unit = 'bottle', package_size = 1.0 WHERE name = 'Zymox Otic with 1% Hydrocortisone 1.25oz bottle';

SELECT COUNT(*) FROM products WHERE dispensing_unit IS NOT NULL;